/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { PushSettings, SubscribePushDto, UpdatePushSettingsDto, VapidKeyResponse } from '.././model';

import { customFetch } from '.././mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getPushControllerGetVapidKeyUrl = () => {
  return `/api/push/vapid-key`;
};

export const pushControllerGetVapidKey = async (options?: RequestInit): Promise<VapidKeyResponse> => {
  return customFetch<VapidKeyResponse>(getPushControllerGetVapidKeyUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getPushControllerGetVapidKeyQueryKey = () => {
  return [`/api/push/vapid-key`] as const;
};

export const getPushControllerGetVapidKeyQueryOptions = <
  TData = Awaited<ReturnType<typeof pushControllerGetVapidKey>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof pushControllerGetVapidKey>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPushControllerGetVapidKeyQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof pushControllerGetVapidKey>>> = ({ signal }) =>
    pushControllerGetVapidKey({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof pushControllerGetVapidKey>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PushControllerGetVapidKeyQueryResult = NonNullable<Awaited<ReturnType<typeof pushControllerGetVapidKey>>>;
export type PushControllerGetVapidKeyQueryError = unknown;

export function usePushControllerGetVapidKey<
  TData = Awaited<ReturnType<typeof pushControllerGetVapidKey>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof pushControllerGetVapidKey>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pushControllerGetVapidKey>>,
          TError,
          Awaited<ReturnType<typeof pushControllerGetVapidKey>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePushControllerGetVapidKey<
  TData = Awaited<ReturnType<typeof pushControllerGetVapidKey>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof pushControllerGetVapidKey>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pushControllerGetVapidKey>>,
          TError,
          Awaited<ReturnType<typeof pushControllerGetVapidKey>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePushControllerGetVapidKey<
  TData = Awaited<ReturnType<typeof pushControllerGetVapidKey>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof pushControllerGetVapidKey>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePushControllerGetVapidKey<
  TData = Awaited<ReturnType<typeof pushControllerGetVapidKey>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof pushControllerGetVapidKey>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPushControllerGetVapidKeyQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPushControllerSubscribeUrl = () => {
  return `/api/push/subscribe`;
};

export const pushControllerSubscribe = async (
  subscribePushDto: SubscribePushDto,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getPushControllerSubscribeUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(subscribePushDto),
  });
};

export const getPushControllerSubscribeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pushControllerSubscribe>>,
    TError,
    { data: SubscribePushDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pushControllerSubscribe>>,
  TError,
  { data: SubscribePushDto },
  TContext
> => {
  const mutationKey = ['pushControllerSubscribe'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pushControllerSubscribe>>,
    { data: SubscribePushDto }
  > = (props) => {
    const { data } = props ?? {};

    return pushControllerSubscribe(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PushControllerSubscribeMutationResult = NonNullable<Awaited<ReturnType<typeof pushControllerSubscribe>>>;
export type PushControllerSubscribeMutationBody = SubscribePushDto;
export type PushControllerSubscribeMutationError = unknown;

export const usePushControllerSubscribe = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pushControllerSubscribe>>,
      TError,
      { data: SubscribePushDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pushControllerSubscribe>>,
  TError,
  { data: SubscribePushDto },
  TContext
> => {
  const mutationOptions = getPushControllerSubscribeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getPushControllerUnsubscribeUrl = () => {
  return `/api/push/subscribe`;
};

export const pushControllerUnsubscribe = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getPushControllerUnsubscribeUrl(), {
    ...options,
    method: 'DELETE',
  });
};

export const getPushControllerUnsubscribeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof pushControllerUnsubscribe>>, TError, void, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof pushControllerUnsubscribe>>, TError, void, TContext> => {
  const mutationKey = ['pushControllerUnsubscribe'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof pushControllerUnsubscribe>>, void> = () => {
    return pushControllerUnsubscribe(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PushControllerUnsubscribeMutationResult = NonNullable<
  Awaited<ReturnType<typeof pushControllerUnsubscribe>>
>;

export type PushControllerUnsubscribeMutationError = unknown;

export const usePushControllerUnsubscribe = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof pushControllerUnsubscribe>>, TError, void, TContext>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof pushControllerUnsubscribe>>, TError, void, TContext> => {
  const mutationOptions = getPushControllerUnsubscribeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getPushControllerGetSettingsUrl = () => {
  return `/api/push/settings`;
};

export const pushControllerGetSettings = async (options?: RequestInit): Promise<PushSettings> => {
  return customFetch<PushSettings>(getPushControllerGetSettingsUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getPushControllerGetSettingsQueryKey = () => {
  return [`/api/push/settings`] as const;
};

export const getPushControllerGetSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof pushControllerGetSettings>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof pushControllerGetSettings>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPushControllerGetSettingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof pushControllerGetSettings>>> = ({ signal }) =>
    pushControllerGetSettings({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof pushControllerGetSettings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PushControllerGetSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof pushControllerGetSettings>>>;
export type PushControllerGetSettingsQueryError = unknown;

export function usePushControllerGetSettings<
  TData = Awaited<ReturnType<typeof pushControllerGetSettings>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof pushControllerGetSettings>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pushControllerGetSettings>>,
          TError,
          Awaited<ReturnType<typeof pushControllerGetSettings>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePushControllerGetSettings<
  TData = Awaited<ReturnType<typeof pushControllerGetSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof pushControllerGetSettings>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pushControllerGetSettings>>,
          TError,
          Awaited<ReturnType<typeof pushControllerGetSettings>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePushControllerGetSettings<
  TData = Awaited<ReturnType<typeof pushControllerGetSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof pushControllerGetSettings>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePushControllerGetSettings<
  TData = Awaited<ReturnType<typeof pushControllerGetSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof pushControllerGetSettings>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPushControllerGetSettingsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPushControllerUpdateSettingsUrl = () => {
  return `/api/push/settings`;
};

export const pushControllerUpdateSettings = async (
  updatePushSettingsDto: UpdatePushSettingsDto,
  options?: RequestInit,
): Promise<PushSettings> => {
  return customFetch<PushSettings>(getPushControllerUpdateSettingsUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePushSettingsDto),
  });
};

export const getPushControllerUpdateSettingsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pushControllerUpdateSettings>>,
    TError,
    { data: UpdatePushSettingsDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pushControllerUpdateSettings>>,
  TError,
  { data: UpdatePushSettingsDto },
  TContext
> => {
  const mutationKey = ['pushControllerUpdateSettings'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pushControllerUpdateSettings>>,
    { data: UpdatePushSettingsDto }
  > = (props) => {
    const { data } = props ?? {};

    return pushControllerUpdateSettings(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PushControllerUpdateSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof pushControllerUpdateSettings>>
>;
export type PushControllerUpdateSettingsMutationBody = UpdatePushSettingsDto;
export type PushControllerUpdateSettingsMutationError = unknown;

export const usePushControllerUpdateSettings = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pushControllerUpdateSettings>>,
      TError,
      { data: UpdatePushSettingsDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pushControllerUpdateSettings>>,
  TError,
  { data: UpdatePushSettingsDto },
  TContext
> => {
  const mutationOptions = getPushControllerUpdateSettingsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
