/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AuthControllerExchangeBody,
  AuthControllerGuestLogin200,
  DeleteAccountDto,
  GuestLoginDto,
  LoginDto,
  RegisterDto,
  UpdateNicknameDto,
  UpdatePasswordDto,
  User,
} from '.././model';

import { customFetch } from '../../lib/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 인증 설정 (Google/CAPTCHA 활성 여부)
 */
export const getAuthControllerGetAuthConfigUrl = () => {
  return `/api/auth/config`;
};

export const authControllerGetAuthConfig = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAuthControllerGetAuthConfigUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getAuthControllerGetAuthConfigQueryKey = () => {
  return [`/api/auth/config`] as const;
};

export const getAuthControllerGetAuthConfigQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetAuthConfig>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetAuthConfig>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerGetAuthConfigQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetAuthConfig>>> = ({ signal }) =>
    authControllerGetAuthConfig({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetAuthConfig>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGetAuthConfigQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetAuthConfig>>
>;
export type AuthControllerGetAuthConfigQueryError = unknown;

export function useAuthControllerGetAuthConfig<
  TData = Awaited<ReturnType<typeof authControllerGetAuthConfig>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetAuthConfig>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetAuthConfig>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetAuthConfig>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGetAuthConfig<
  TData = Awaited<ReturnType<typeof authControllerGetAuthConfig>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetAuthConfig>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetAuthConfig>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetAuthConfig>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGetAuthConfig<
  TData = Awaited<ReturnType<typeof authControllerGetAuthConfig>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetAuthConfig>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 인증 설정 (Google/CAPTCHA 활성 여부)
 */

export function useAuthControllerGetAuthConfig<
  TData = Awaited<ReturnType<typeof authControllerGetAuthConfig>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetAuthConfig>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthControllerGetAuthConfigQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Google OAuth 로그인 시작
 */
export const getAuthControllerGoogleLoginUrl = () => {
  return `/api/auth/google`;
};

export const authControllerGoogleLogin = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAuthControllerGoogleLoginUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getAuthControllerGoogleLoginQueryKey = () => {
  return [`/api/auth/google`] as const;
};

export const getAuthControllerGoogleLoginQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGoogleLogin>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerGoogleLoginQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGoogleLogin>>> = ({ signal }) =>
    authControllerGoogleLogin({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGoogleLogin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGoogleLoginQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerGoogleLogin>>>;
export type AuthControllerGoogleLoginQueryError = unknown;

export function useAuthControllerGoogleLogin<
  TData = Awaited<ReturnType<typeof authControllerGoogleLogin>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleLogin>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGoogleLogin<
  TData = Awaited<ReturnType<typeof authControllerGoogleLogin>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleLogin>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGoogleLogin<
  TData = Awaited<ReturnType<typeof authControllerGoogleLogin>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Google OAuth 로그인 시작
 */

export function useAuthControllerGoogleLogin<
  TData = Awaited<ReturnType<typeof authControllerGoogleLogin>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleLogin>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthControllerGoogleLoginQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Google 계정 연동 시작
 */
export const getAuthControllerStartLinkGoogleUrl = () => {
  return `/api/auth/link-google`;
};

export const authControllerStartLinkGoogle = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAuthControllerStartLinkGoogleUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getAuthControllerStartLinkGoogleQueryKey = () => {
  return [`/api/auth/link-google`] as const;
};

export const getAuthControllerStartLinkGoogleQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerStartLinkGoogle>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStartLinkGoogle>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerStartLinkGoogleQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerStartLinkGoogle>>> = ({ signal }) =>
    authControllerStartLinkGoogle({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerStartLinkGoogle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerStartLinkGoogleQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerStartLinkGoogle>>
>;
export type AuthControllerStartLinkGoogleQueryError = unknown;

export function useAuthControllerStartLinkGoogle<
  TData = Awaited<ReturnType<typeof authControllerStartLinkGoogle>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStartLinkGoogle>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerStartLinkGoogle>>,
          TError,
          Awaited<ReturnType<typeof authControllerStartLinkGoogle>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerStartLinkGoogle<
  TData = Awaited<ReturnType<typeof authControllerStartLinkGoogle>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStartLinkGoogle>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerStartLinkGoogle>>,
          TError,
          Awaited<ReturnType<typeof authControllerStartLinkGoogle>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerStartLinkGoogle<
  TData = Awaited<ReturnType<typeof authControllerStartLinkGoogle>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStartLinkGoogle>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Google 계정 연동 시작
 */

export function useAuthControllerStartLinkGoogle<
  TData = Awaited<ReturnType<typeof authControllerStartLinkGoogle>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerStartLinkGoogle>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthControllerStartLinkGoogleQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Google OAuth 콜백
 */
export const getAuthControllerGoogleCallbackUrl = () => {
  return `/api/auth/google/callback`;
};

export const authControllerGoogleCallback = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAuthControllerGoogleCallbackUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getAuthControllerGoogleCallbackQueryKey = () => {
  return [`/api/auth/google/callback`] as const;
};

export const getAuthControllerGoogleCallbackQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGoogleCallback>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerGoogleCallbackQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGoogleCallback>>> = ({ signal }) =>
    authControllerGoogleCallback({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGoogleCallback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGoogleCallbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGoogleCallback>>
>;
export type AuthControllerGoogleCallbackQueryError = unknown;

export function useAuthControllerGoogleCallback<
  TData = Awaited<ReturnType<typeof authControllerGoogleCallback>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleCallback>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGoogleCallback<
  TData = Awaited<ReturnType<typeof authControllerGoogleCallback>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleCallback>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGoogleCallback<
  TData = Awaited<ReturnType<typeof authControllerGoogleCallback>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Google OAuth 콜백
 */

export function useAuthControllerGoogleCallback<
  TData = Awaited<ReturnType<typeof authControllerGoogleCallback>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleCallback>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthControllerGoogleCallbackQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary OAuth 코드 → 쿠키 교환
 */
export const getAuthControllerExchangeUrl = () => {
  return `/api/auth/exchange`;
};

export const authControllerExchange = async (
  authControllerExchangeBody: AuthControllerExchangeBody,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getAuthControllerExchangeUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authControllerExchangeBody),
  });
};

export const getAuthControllerExchangeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerExchange>>,
    TError,
    { data: AuthControllerExchangeBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerExchange>>,
  TError,
  { data: AuthControllerExchangeBody },
  TContext
> => {
  const mutationKey = ['authControllerExchange'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerExchange>>,
    { data: AuthControllerExchangeBody }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerExchange(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerExchangeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerExchange>>>;
export type AuthControllerExchangeMutationBody = AuthControllerExchangeBody;
export type AuthControllerExchangeMutationError = unknown;

/**
 * @summary OAuth 코드 → 쿠키 교환
 */
export const useAuthControllerExchange = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerExchange>>,
      TError,
      { data: AuthControllerExchangeBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerExchange>>,
  TError,
  { data: AuthControllerExchangeBody },
  TContext
> => {
  const mutationOptions = getAuthControllerExchangeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 토큰 갱신 (쿠키 기반)
 */
export const getAuthControllerRefreshUrl = () => {
  return `/api/auth/refresh`;
};

export const authControllerRefresh = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAuthControllerRefreshUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getAuthControllerRefreshMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError, void, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError, void, TContext> => {
  const mutationKey = ['authControllerRefresh'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRefresh>>, void> = () => {
    return authControllerRefresh(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRefresh>>>;

export type AuthControllerRefreshMutationError = unknown;

/**
 * @summary 토큰 갱신 (쿠키 기반)
 */
export const useAuthControllerRefresh = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError, void, TContext>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof authControllerRefresh>>, TError, void, TContext> => {
  const mutationOptions = getAuthControllerRefreshMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 로그아웃 (쿠키 삭제 + refresh token 무효화)
 */
export const getAuthControllerLogoutUrl = () => {
  return `/api/auth/logout`;
};

export const authControllerLogout = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAuthControllerLogoutUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getAuthControllerLogoutMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError, void, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError, void, TContext> => {
  const mutationKey = ['authControllerLogout'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogout>>, void> = () => {
    return authControllerLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>;

export type AuthControllerLogoutMutationError = unknown;

/**
 * @summary 로그아웃 (쿠키 삭제 + refresh token 무효화)
 */
export const useAuthControllerLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError, void, TContext>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof authControllerLogout>>, TError, void, TContext> => {
  const mutationOptions = getAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 초대코드로 게스트 입장
 */
export const getAuthControllerGuestLoginUrl = () => {
  return `/api/auth/guest`;
};

export const authControllerGuestLogin = async (
  guestLoginDto: GuestLoginDto,
  options?: RequestInit,
): Promise<AuthControllerGuestLogin200> => {
  return customFetch<AuthControllerGuestLogin200>(getAuthControllerGuestLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(guestLoginDto),
  });
};

export const getAuthControllerGuestLoginMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerGuestLogin>>,
    TError,
    { data: GuestLoginDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerGuestLogin>>,
  TError,
  { data: GuestLoginDto },
  TContext
> => {
  const mutationKey = ['authControllerGuestLogin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerGuestLogin>>, { data: GuestLoginDto }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return authControllerGuestLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerGuestLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerGuestLogin>>>;
export type AuthControllerGuestLoginMutationBody = GuestLoginDto;
export type AuthControllerGuestLoginMutationError = unknown;

/**
 * @summary 초대코드로 게스트 입장
 */
export const useAuthControllerGuestLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerGuestLogin>>,
      TError,
      { data: GuestLoginDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerGuestLogin>>,
  TError,
  { data: GuestLoginDto },
  TContext
> => {
  const mutationOptions = getAuthControllerGuestLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 회원가입 (초대코드 필요)
 */
export const getAuthControllerRegisterUrl = () => {
  return `/api/auth/register`;
};

export const authControllerRegister = async (registerDto: RegisterDto, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAuthControllerRegisterUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerDto),
  });
};

export const getAuthControllerRegisterMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegister>>,
    TError,
    { data: RegisterDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, { data: RegisterDto }, TContext> => {
  const mutationKey = ['authControllerRegister'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRegister>>, { data: RegisterDto }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return authControllerRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>;
export type AuthControllerRegisterMutationBody = RegisterDto;
export type AuthControllerRegisterMutationError = unknown;

/**
 * @summary 회원가입 (초대코드 필요)
 */
export const useAuthControllerRegister = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRegister>>,
      TError,
      { data: RegisterDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof authControllerRegister>>, TError, { data: RegisterDto }, TContext> => {
  const mutationOptions = getAuthControllerRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 로그인
 */
export const getAuthControllerLoginUrl = () => {
  return `/api/auth/login`;
};

export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAuthControllerLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginDto),
  });
};

export const getAuthControllerLoginMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, { data: LoginDto }, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, { data: LoginDto }, TContext> => {
  const mutationKey = ['authControllerLogin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogin>>, { data: LoginDto }> = (props) => {
    const { data } = props ?? {};

    return authControllerLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>;
export type AuthControllerLoginMutationBody = LoginDto;
export type AuthControllerLoginMutationError = unknown;

/**
 * @summary 로그인
 */
export const useAuthControllerLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogin>>,
      TError,
      { data: LoginDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof authControllerLogin>>, TError, { data: LoginDto }, TContext> => {
  const mutationOptions = getAuthControllerLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 닉네임 변경
 */
export const getAuthControllerUpdateNicknameUrl = () => {
  return `/api/auth/profile/nickname`;
};

export const authControllerUpdateNickname = async (
  updateNicknameDto: UpdateNicknameDto,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getAuthControllerUpdateNicknameUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateNicknameDto),
  });
};

export const getAuthControllerUpdateNicknameMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerUpdateNickname>>,
    TError,
    { data: UpdateNicknameDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerUpdateNickname>>,
  TError,
  { data: UpdateNicknameDto },
  TContext
> => {
  const mutationKey = ['authControllerUpdateNickname'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerUpdateNickname>>,
    { data: UpdateNicknameDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerUpdateNickname(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerUpdateNicknameMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerUpdateNickname>>
>;
export type AuthControllerUpdateNicknameMutationBody = UpdateNicknameDto;
export type AuthControllerUpdateNicknameMutationError = unknown;

/**
 * @summary 닉네임 변경
 */
export const useAuthControllerUpdateNickname = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerUpdateNickname>>,
      TError,
      { data: UpdateNicknameDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerUpdateNickname>>,
  TError,
  { data: UpdateNicknameDto },
  TContext
> => {
  const mutationOptions = getAuthControllerUpdateNicknameMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 비밀번호 변경
 */
export const getAuthControllerUpdatePasswordUrl = () => {
  return `/api/auth/profile/password`;
};

export const authControllerUpdatePassword = async (
  updatePasswordDto: UpdatePasswordDto,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getAuthControllerUpdatePasswordUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePasswordDto),
  });
};

export const getAuthControllerUpdatePasswordMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerUpdatePassword>>,
    TError,
    { data: UpdatePasswordDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerUpdatePassword>>,
  TError,
  { data: UpdatePasswordDto },
  TContext
> => {
  const mutationKey = ['authControllerUpdatePassword'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerUpdatePassword>>,
    { data: UpdatePasswordDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerUpdatePassword(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerUpdatePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerUpdatePassword>>
>;
export type AuthControllerUpdatePasswordMutationBody = UpdatePasswordDto;
export type AuthControllerUpdatePasswordMutationError = unknown;

/**
 * @summary 비밀번호 변경
 */
export const useAuthControllerUpdatePassword = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerUpdatePassword>>,
      TError,
      { data: UpdatePasswordDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerUpdatePassword>>,
  TError,
  { data: UpdatePasswordDto },
  TContext
> => {
  const mutationOptions = getAuthControllerUpdatePasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 회원 탈퇴
 */
export const getAuthControllerDeleteAccountUrl = () => {
  return `/api/auth/account`;
};

export const authControllerDeleteAccount = async (
  deleteAccountDto: DeleteAccountDto,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getAuthControllerDeleteAccountUrl(), {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteAccountDto),
  });
};

export const getAuthControllerDeleteAccountMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerDeleteAccount>>,
    TError,
    { data: DeleteAccountDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerDeleteAccount>>,
  TError,
  { data: DeleteAccountDto },
  TContext
> => {
  const mutationKey = ['authControllerDeleteAccount'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerDeleteAccount>>,
    { data: DeleteAccountDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerDeleteAccount(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerDeleteAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerDeleteAccount>>
>;
export type AuthControllerDeleteAccountMutationBody = DeleteAccountDto;
export type AuthControllerDeleteAccountMutationError = unknown;

/**
 * @summary 회원 탈퇴
 */
export const useAuthControllerDeleteAccount = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerDeleteAccount>>,
      TError,
      { data: DeleteAccountDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerDeleteAccount>>,
  TError,
  { data: DeleteAccountDto },
  TContext
> => {
  const mutationOptions = getAuthControllerDeleteAccountMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 현재 사용자 정보
 */
export const getAuthControllerMeUrl = () => {
  return `/api/auth/me`;
};

export const authControllerMe = async (options?: RequestInit): Promise<User> => {
  return customFetch<User>(getAuthControllerMeUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getAuthControllerMeQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getAuthControllerMeQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerMe>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerMe>>> = ({ signal }) =>
    authControllerMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerMeQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerMe>>>;
export type AuthControllerMeQueryError = unknown;

export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMe>>,
          TError,
          Awaited<ReturnType<typeof authControllerMe>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMe>>,
          TError,
          Awaited<ReturnType<typeof authControllerMe>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 현재 사용자 정보
 */

export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthControllerMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
