/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  BanInfo,
  CreateRoomDto,
  JoinRoomDto,
  MyPermissionsResponse,
  ResetBansResponse,
  Room,
  RoomDetail,
  RoomListItem,
  RoomMember,
  RoomPermission,
  RoomsControllerLeave201,
  SanctionsResponse,
  UpdatePermissionsBody,
  UpdateRoomDto,
} from '.././model';

import { customFetch } from '.././mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 방 생성
 */
export const getRoomsControllerCreateUrl = () => {
  return `/api/rooms`;
};

export const roomsControllerCreate = async (createRoomDto: CreateRoomDto, options?: RequestInit): Promise<Room> => {
  return customFetch<Room>(getRoomsControllerCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRoomDto),
  });
};

export const getRoomsControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsControllerCreate>>,
    TError,
    { data: CreateRoomDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsControllerCreate>>,
  TError,
  { data: CreateRoomDto },
  TContext
> => {
  const mutationKey = ['roomsControllerCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof roomsControllerCreate>>, { data: CreateRoomDto }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return roomsControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof roomsControllerCreate>>>;
export type RoomsControllerCreateMutationBody = CreateRoomDto;
export type RoomsControllerCreateMutationError = unknown;

/**
 * @summary 방 생성
 */
export const useRoomsControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerCreate>>,
      TError,
      { data: CreateRoomDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof roomsControllerCreate>>, TError, { data: CreateRoomDto }, TContext> => {
  const mutationOptions = getRoomsControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 활성 방 목록
 */
export const getRoomsControllerFindAllUrl = () => {
  return `/api/rooms`;
};

export const roomsControllerFindAll = async (options?: RequestInit): Promise<RoomListItem[]> => {
  return customFetch<RoomListItem[]>(getRoomsControllerFindAllUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getRoomsControllerFindAllQueryKey = () => {
  return [`/api/rooms`] as const;
};

export const getRoomsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof roomsControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerFindAll>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRoomsControllerFindAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof roomsControllerFindAll>>> = ({ signal }) =>
    roomsControllerFindAll({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof roomsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RoomsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof roomsControllerFindAll>>>;
export type RoomsControllerFindAllQueryError = unknown;

export function useRoomsControllerFindAll<TData = Awaited<ReturnType<typeof roomsControllerFindAll>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof roomsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof roomsControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRoomsControllerFindAll<TData = Awaited<ReturnType<typeof roomsControllerFindAll>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof roomsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof roomsControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRoomsControllerFindAll<TData = Awaited<ReturnType<typeof roomsControllerFindAll>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerFindAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 활성 방 목록
 */

export function useRoomsControllerFindAll<TData = Awaited<ReturnType<typeof roomsControllerFindAll>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerFindAll>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRoomsControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 방 상세 조회
 */
export const getRoomsControllerFindOneUrl = (id: string) => {
  return `/api/rooms/${id}`;
};

export const roomsControllerFindOne = async (id: string, options?: RequestInit): Promise<RoomDetail> => {
  return customFetch<RoomDetail>(getRoomsControllerFindOneUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getRoomsControllerFindOneQueryKey = (id?: string) => {
  return [`/api/rooms/${id}`] as const;
};

export const getRoomsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof roomsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRoomsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof roomsControllerFindOne>>> = ({ signal }) =>
    roomsControllerFindOne(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof roomsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RoomsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof roomsControllerFindOne>>>;
export type RoomsControllerFindOneQueryError = unknown;

export function useRoomsControllerFindOne<TData = Awaited<ReturnType<typeof roomsControllerFindOne>>, TError = unknown>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerFindOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof roomsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof roomsControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRoomsControllerFindOne<TData = Awaited<ReturnType<typeof roomsControllerFindOne>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerFindOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof roomsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof roomsControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRoomsControllerFindOne<TData = Awaited<ReturnType<typeof roomsControllerFindOne>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 방 상세 조회
 */

export function useRoomsControllerFindOne<TData = Awaited<ReturnType<typeof roomsControllerFindOne>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRoomsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 방 설정 수정
 */
export const getRoomsControllerUpdateUrl = (id: string) => {
  return `/api/rooms/${id}`;
};

export const roomsControllerUpdate = async (
  id: string,
  updateRoomDto: UpdateRoomDto,
  options?: RequestInit,
): Promise<Room> => {
  return customFetch<Room>(getRoomsControllerUpdateUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateRoomDto),
  });
};

export const getRoomsControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsControllerUpdate>>,
    TError,
    { id: string; data: UpdateRoomDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsControllerUpdate>>,
  TError,
  { id: string; data: UpdateRoomDto },
  TContext
> => {
  const mutationKey = ['roomsControllerUpdate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsControllerUpdate>>,
    { id: string; data: UpdateRoomDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return roomsControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof roomsControllerUpdate>>>;
export type RoomsControllerUpdateMutationBody = UpdateRoomDto;
export type RoomsControllerUpdateMutationError = unknown;

/**
 * @summary 방 설정 수정
 */
export const useRoomsControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerUpdate>>,
      TError,
      { id: string; data: UpdateRoomDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof roomsControllerUpdate>>,
  TError,
  { id: string; data: UpdateRoomDto },
  TContext
> => {
  const mutationOptions = getRoomsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 방 삭제
 */
export const getRoomsControllerRemoveUrl = (id: string) => {
  return `/api/rooms/${id}`;
};

export const roomsControllerRemove = async (id: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getRoomsControllerRemoveUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getRoomsControllerRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof roomsControllerRemove>>, TError, { id: string }, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof roomsControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationKey = ['roomsControllerRemove'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof roomsControllerRemove>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return roomsControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof roomsControllerRemove>>>;

export type RoomsControllerRemoveMutationError = unknown;

/**
 * @summary 방 삭제
 */
export const useRoomsControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof roomsControllerRemove>>, TError, { id: string }, TContext>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof roomsControllerRemove>>, TError, { id: string }, TContext> => {
  const mutationOptions = getRoomsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 방 입장
 */
export const getRoomsControllerJoinUrl = (id: string) => {
  return `/api/rooms/${id}/join`;
};

export const roomsControllerJoin = async (
  id: string,
  joinRoomDto: JoinRoomDto,
  options?: RequestInit,
): Promise<RoomMember> => {
  return customFetch<RoomMember>(getRoomsControllerJoinUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(joinRoomDto),
  });
};

export const getRoomsControllerJoinMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsControllerJoin>>,
    TError,
    { id: string; data: JoinRoomDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsControllerJoin>>,
  TError,
  { id: string; data: JoinRoomDto },
  TContext
> => {
  const mutationKey = ['roomsControllerJoin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsControllerJoin>>,
    { id: string; data: JoinRoomDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return roomsControllerJoin(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerJoinMutationResult = NonNullable<Awaited<ReturnType<typeof roomsControllerJoin>>>;
export type RoomsControllerJoinMutationBody = JoinRoomDto;
export type RoomsControllerJoinMutationError = unknown;

/**
 * @summary 방 입장
 */
export const useRoomsControllerJoin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerJoin>>,
      TError,
      { id: string; data: JoinRoomDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof roomsControllerJoin>>,
  TError,
  { id: string; data: JoinRoomDto },
  TContext
> => {
  const mutationOptions = getRoomsControllerJoinMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 방 퇴장
 */
export const getRoomsControllerLeaveUrl = (id: string) => {
  return `/api/rooms/${id}/leave`;
};

export const roomsControllerLeave = async (id: string, options?: RequestInit): Promise<RoomsControllerLeave201> => {
  return customFetch<RoomsControllerLeave201>(getRoomsControllerLeaveUrl(id), {
    ...options,
    method: 'POST',
  });
};

export const getRoomsControllerLeaveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof roomsControllerLeave>>, TError, { id: string }, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof roomsControllerLeave>>, TError, { id: string }, TContext> => {
  const mutationKey = ['roomsControllerLeave'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof roomsControllerLeave>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return roomsControllerLeave(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerLeaveMutationResult = NonNullable<Awaited<ReturnType<typeof roomsControllerLeave>>>;

export type RoomsControllerLeaveMutationError = unknown;

/**
 * @summary 방 퇴장
 */
export const useRoomsControllerLeave = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof roomsControllerLeave>>, TError, { id: string }, TContext>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof roomsControllerLeave>>, TError, { id: string }, TContext> => {
  const mutationOptions = getRoomsControllerLeaveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 내 실효 권한 조회
 */
export const getRoomsControllerGetMyPermissionsUrl = (id: string) => {
  return `/api/rooms/${id}/my-permissions`;
};

export const roomsControllerGetMyPermissions = async (
  id: string,
  options?: RequestInit,
): Promise<MyPermissionsResponse> => {
  return customFetch<MyPermissionsResponse>(getRoomsControllerGetMyPermissionsUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getRoomsControllerGetMyPermissionsQueryKey = (id?: string) => {
  return [`/api/rooms/${id}/my-permissions`] as const;
};

export const getRoomsControllerGetMyPermissionsQueryOptions = <
  TData = Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRoomsControllerGetMyPermissionsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>> = ({ signal }) =>
    roomsControllerGetMyPermissions(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RoomsControllerGetMyPermissionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>
>;
export type RoomsControllerGetMyPermissionsQueryError = unknown;

export function useRoomsControllerGetMyPermissions<
  TData = Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>,
          TError,
          Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRoomsControllerGetMyPermissions<
  TData = Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>,
          TError,
          Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRoomsControllerGetMyPermissions<
  TData = Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 내 실효 권한 조회
 */

export function useRoomsControllerGetMyPermissions<
  TData = Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetMyPermissions>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRoomsControllerGetMyPermissionsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 멤버 권한 수정
 */
export const getRoomsControllerUpdatePermissionsUrl = (id: string, userId: string) => {
  return `/api/rooms/${id}/members/${userId}/permissions`;
};

export const roomsControllerUpdatePermissions = async (
  id: string,
  userId: string,
  updatePermissionsBody: UpdatePermissionsBody,
  options?: RequestInit,
): Promise<RoomPermission> => {
  return customFetch<RoomPermission>(getRoomsControllerUpdatePermissionsUrl(id, userId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePermissionsBody),
  });
};

export const getRoomsControllerUpdatePermissionsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsControllerUpdatePermissions>>,
    TError,
    { id: string; userId: string; data: UpdatePermissionsBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsControllerUpdatePermissions>>,
  TError,
  { id: string; userId: string; data: UpdatePermissionsBody },
  TContext
> => {
  const mutationKey = ['roomsControllerUpdatePermissions'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsControllerUpdatePermissions>>,
    { id: string; userId: string; data: UpdatePermissionsBody }
  > = (props) => {
    const { id, userId, data } = props ?? {};

    return roomsControllerUpdatePermissions(id, userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerUpdatePermissionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof roomsControllerUpdatePermissions>>
>;
export type RoomsControllerUpdatePermissionsMutationBody = UpdatePermissionsBody;
export type RoomsControllerUpdatePermissionsMutationError = unknown;

/**
 * @summary 멤버 권한 수정
 */
export const useRoomsControllerUpdatePermissions = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerUpdatePermissions>>,
      TError,
      { id: string; userId: string; data: UpdatePermissionsBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof roomsControllerUpdatePermissions>>,
  TError,
  { id: string; userId: string; data: UpdatePermissionsBody },
  TContext
> => {
  const mutationOptions = getRoomsControllerUpdatePermissionsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 곡 신청 횟수 초기화
 */
export const getRoomsControllerResetEnqueueCountsUrl = (id: string) => {
  return `/api/rooms/${id}/reset-enqueue-counts`;
};

export const roomsControllerResetEnqueueCounts = async (id: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getRoomsControllerResetEnqueueCountsUrl(id), {
    ...options,
    method: 'POST',
  });
};

export const getRoomsControllerResetEnqueueCountsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsControllerResetEnqueueCounts>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsControllerResetEnqueueCounts>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['roomsControllerResetEnqueueCounts'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof roomsControllerResetEnqueueCounts>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return roomsControllerResetEnqueueCounts(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerResetEnqueueCountsMutationResult = NonNullable<
  Awaited<ReturnType<typeof roomsControllerResetEnqueueCounts>>
>;

export type RoomsControllerResetEnqueueCountsMutationError = unknown;

/**
 * @summary 곡 신청 횟수 초기화
 */
export const useRoomsControllerResetEnqueueCounts = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerResetEnqueueCounts>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof roomsControllerResetEnqueueCounts>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getRoomsControllerResetEnqueueCountsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary DJ 위임
 */
export const getRoomsControllerTransferHostUrl = (id: string, userId: string) => {
  return `/api/rooms/${id}/transfer-host/${userId}`;
};

export const roomsControllerTransferHost = async (id: string, userId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getRoomsControllerTransferHostUrl(id, userId), {
    ...options,
    method: 'POST',
  });
};

export const getRoomsControllerTransferHostMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsControllerTransferHost>>,
    TError,
    { id: string; userId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsControllerTransferHost>>,
  TError,
  { id: string; userId: string },
  TContext
> => {
  const mutationKey = ['roomsControllerTransferHost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsControllerTransferHost>>,
    { id: string; userId: string }
  > = (props) => {
    const { id, userId } = props ?? {};

    return roomsControllerTransferHost(id, userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerTransferHostMutationResult = NonNullable<
  Awaited<ReturnType<typeof roomsControllerTransferHost>>
>;

export type RoomsControllerTransferHostMutationError = unknown;

/**
 * @summary DJ 위임
 */
export const useRoomsControllerTransferHost = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerTransferHost>>,
      TError,
      { id: string; userId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof roomsControllerTransferHost>>,
  TError,
  { id: string; userId: string },
  TContext
> => {
  const mutationOptions = getRoomsControllerTransferHostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 멤버 추방
 */
export const getRoomsControllerKickUrl = (id: string, userId: string) => {
  return `/api/rooms/${id}/kick/${userId}`;
};

export const roomsControllerKick = async (id: string, userId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getRoomsControllerKickUrl(id, userId), {
    ...options,
    method: 'POST',
  });
};

export const getRoomsControllerKickMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsControllerKick>>,
    TError,
    { id: string; userId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsControllerKick>>,
  TError,
  { id: string; userId: string },
  TContext
> => {
  const mutationKey = ['roomsControllerKick'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsControllerKick>>,
    { id: string; userId: string }
  > = (props) => {
    const { id, userId } = props ?? {};

    return roomsControllerKick(id, userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerKickMutationResult = NonNullable<Awaited<ReturnType<typeof roomsControllerKick>>>;

export type RoomsControllerKickMutationError = unknown;

/**
 * @summary 멤버 추방
 */
export const useRoomsControllerKick = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerKick>>,
      TError,
      { id: string; userId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof roomsControllerKick>>,
  TError,
  { id: string; userId: string },
  TContext
> => {
  const mutationOptions = getRoomsControllerKickMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 밴 초기화
 */
export const getRoomsControllerResetBansUrl = (id: string) => {
  return `/api/rooms/${id}/reset-bans`;
};

export const roomsControllerResetBans = async (id: string, options?: RequestInit): Promise<ResetBansResponse> => {
  return customFetch<ResetBansResponse>(getRoomsControllerResetBansUrl(id), {
    ...options,
    method: 'POST',
  });
};

export const getRoomsControllerResetBansMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof roomsControllerResetBans>>, TError, { id: string }, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof roomsControllerResetBans>>, TError, { id: string }, TContext> => {
  const mutationKey = ['roomsControllerResetBans'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof roomsControllerResetBans>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return roomsControllerResetBans(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerResetBansMutationResult = NonNullable<Awaited<ReturnType<typeof roomsControllerResetBans>>>;

export type RoomsControllerResetBansMutationError = unknown;

/**
 * @summary 밴 초기화
 */
export const useRoomsControllerResetBans = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerResetBans>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof roomsControllerResetBans>>, TError, { id: string }, TContext> => {
  const mutationOptions = getRoomsControllerResetBansMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 밴 목록 조회
 */
export const getRoomsControllerGetBansUrl = (id: string) => {
  return `/api/rooms/${id}/bans`;
};

export const roomsControllerGetBans = async (id: string, options?: RequestInit): Promise<BanInfo[]> => {
  return customFetch<BanInfo[]>(getRoomsControllerGetBansUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getRoomsControllerGetBansQueryKey = (id?: string) => {
  return [`/api/rooms/${id}/bans`] as const;
};

export const getRoomsControllerGetBansQueryOptions = <
  TData = Awaited<ReturnType<typeof roomsControllerGetBans>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetBans>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRoomsControllerGetBansQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof roomsControllerGetBans>>> = ({ signal }) =>
    roomsControllerGetBans(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof roomsControllerGetBans>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RoomsControllerGetBansQueryResult = NonNullable<Awaited<ReturnType<typeof roomsControllerGetBans>>>;
export type RoomsControllerGetBansQueryError = unknown;

export function useRoomsControllerGetBans<TData = Awaited<ReturnType<typeof roomsControllerGetBans>>, TError = unknown>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetBans>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof roomsControllerGetBans>>,
          TError,
          Awaited<ReturnType<typeof roomsControllerGetBans>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRoomsControllerGetBans<TData = Awaited<ReturnType<typeof roomsControllerGetBans>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetBans>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof roomsControllerGetBans>>,
          TError,
          Awaited<ReturnType<typeof roomsControllerGetBans>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRoomsControllerGetBans<TData = Awaited<ReturnType<typeof roomsControllerGetBans>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetBans>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 밴 목록 조회
 */

export function useRoomsControllerGetBans<TData = Awaited<ReturnType<typeof roomsControllerGetBans>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetBans>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRoomsControllerGetBansQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 밴 해제
 */
export const getRoomsControllerUnbanUrl = (id: string, userId: string) => {
  return `/api/rooms/${id}/bans/${userId}`;
};

export const roomsControllerUnban = async (id: string, userId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getRoomsControllerUnbanUrl(id, userId), {
    ...options,
    method: 'DELETE',
  });
};

export const getRoomsControllerUnbanMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsControllerUnban>>,
    TError,
    { id: string; userId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsControllerUnban>>,
  TError,
  { id: string; userId: string },
  TContext
> => {
  const mutationKey = ['roomsControllerUnban'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsControllerUnban>>,
    { id: string; userId: string }
  > = (props) => {
    const { id, userId } = props ?? {};

    return roomsControllerUnban(id, userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerUnbanMutationResult = NonNullable<Awaited<ReturnType<typeof roomsControllerUnban>>>;

export type RoomsControllerUnbanMutationError = unknown;

/**
 * @summary 밴 해제
 */
export const useRoomsControllerUnban = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerUnban>>,
      TError,
      { id: string; userId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof roomsControllerUnban>>,
  TError,
  { id: string; userId: string },
  TContext
> => {
  const mutationOptions = getRoomsControllerUnbanMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 제재 목록 (추방 + 채팅 제한)
 */
export const getRoomsControllerGetSanctionsUrl = (id: string) => {
  return `/api/rooms/${id}/sanctions`;
};

export const roomsControllerGetSanctions = async (id: string, options?: RequestInit): Promise<SanctionsResponse> => {
  return customFetch<SanctionsResponse>(getRoomsControllerGetSanctionsUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getRoomsControllerGetSanctionsQueryKey = (id?: string) => {
  return [`/api/rooms/${id}/sanctions`] as const;
};

export const getRoomsControllerGetSanctionsQueryOptions = <
  TData = Awaited<ReturnType<typeof roomsControllerGetSanctions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetSanctions>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRoomsControllerGetSanctionsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof roomsControllerGetSanctions>>> = ({ signal }) =>
    roomsControllerGetSanctions(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof roomsControllerGetSanctions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RoomsControllerGetSanctionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof roomsControllerGetSanctions>>
>;
export type RoomsControllerGetSanctionsQueryError = unknown;

export function useRoomsControllerGetSanctions<
  TData = Awaited<ReturnType<typeof roomsControllerGetSanctions>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetSanctions>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof roomsControllerGetSanctions>>,
          TError,
          Awaited<ReturnType<typeof roomsControllerGetSanctions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRoomsControllerGetSanctions<
  TData = Awaited<ReturnType<typeof roomsControllerGetSanctions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetSanctions>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof roomsControllerGetSanctions>>,
          TError,
          Awaited<ReturnType<typeof roomsControllerGetSanctions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRoomsControllerGetSanctions<
  TData = Awaited<ReturnType<typeof roomsControllerGetSanctions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetSanctions>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 제재 목록 (추방 + 채팅 제한)
 */

export function useRoomsControllerGetSanctions<
  TData = Awaited<ReturnType<typeof roomsControllerGetSanctions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof roomsControllerGetSanctions>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRoomsControllerGetSanctionsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 채팅 제한
 */
export const getRoomsControllerMuteUserUrl = (id: string, userId: string) => {
  return `/api/rooms/${id}/mute/${userId}`;
};

export const roomsControllerMuteUser = async (id: string, userId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getRoomsControllerMuteUserUrl(id, userId), {
    ...options,
    method: 'POST',
  });
};

export const getRoomsControllerMuteUserMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsControllerMuteUser>>,
    TError,
    { id: string; userId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsControllerMuteUser>>,
  TError,
  { id: string; userId: string },
  TContext
> => {
  const mutationKey = ['roomsControllerMuteUser'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsControllerMuteUser>>,
    { id: string; userId: string }
  > = (props) => {
    const { id, userId } = props ?? {};

    return roomsControllerMuteUser(id, userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerMuteUserMutationResult = NonNullable<Awaited<ReturnType<typeof roomsControllerMuteUser>>>;

export type RoomsControllerMuteUserMutationError = unknown;

/**
 * @summary 채팅 제한
 */
export const useRoomsControllerMuteUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerMuteUser>>,
      TError,
      { id: string; userId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof roomsControllerMuteUser>>,
  TError,
  { id: string; userId: string },
  TContext
> => {
  const mutationOptions = getRoomsControllerMuteUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 채팅 제한 해제
 */
export const getRoomsControllerUnmuteUserUrl = (id: string, userId: string) => {
  return `/api/rooms/${id}/mute/${userId}`;
};

export const roomsControllerUnmuteUser = async (id: string, userId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getRoomsControllerUnmuteUserUrl(id, userId), {
    ...options,
    method: 'DELETE',
  });
};

export const getRoomsControllerUnmuteUserMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof roomsControllerUnmuteUser>>,
    TError,
    { id: string; userId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof roomsControllerUnmuteUser>>,
  TError,
  { id: string; userId: string },
  TContext
> => {
  const mutationKey = ['roomsControllerUnmuteUser'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof roomsControllerUnmuteUser>>,
    { id: string; userId: string }
  > = (props) => {
    const { id, userId } = props ?? {};

    return roomsControllerUnmuteUser(id, userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RoomsControllerUnmuteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof roomsControllerUnmuteUser>>
>;

export type RoomsControllerUnmuteUserMutationError = unknown;

/**
 * @summary 채팅 제한 해제
 */
export const useRoomsControllerUnmuteUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof roomsControllerUnmuteUser>>,
      TError,
      { id: string; userId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof roomsControllerUnmuteUser>>,
  TError,
  { id: string; userId: string },
  TContext
> => {
  const mutationOptions = getRoomsControllerUnmuteUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
