/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AutoDjCandidatesResponse } from '.././model';

import { customFetch } from '.././mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary AutoDJ 후보 조회
 */
export const getAutoDjControllerGetCandidatesUrl = (id: string) => {
  return `/api/rooms/${id}/autodj/candidates`;
};

export const autoDjControllerGetCandidates = async (
  id: string,
  options?: RequestInit,
): Promise<AutoDjCandidatesResponse> => {
  return customFetch<AutoDjCandidatesResponse>(getAutoDjControllerGetCandidatesUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getAutoDjControllerGetCandidatesQueryKey = (id?: string) => {
  return [`/api/rooms/${id}/autodj/candidates`] as const;
};

export const getAutoDjControllerGetCandidatesQueryOptions = <
  TData = Awaited<ReturnType<typeof autoDjControllerGetCandidates>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof autoDjControllerGetCandidates>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAutoDjControllerGetCandidatesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof autoDjControllerGetCandidates>>> = ({ signal }) =>
    autoDjControllerGetCandidates(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof autoDjControllerGetCandidates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AutoDjControllerGetCandidatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof autoDjControllerGetCandidates>>
>;
export type AutoDjControllerGetCandidatesQueryError = unknown;

export function useAutoDjControllerGetCandidates<
  TData = Awaited<ReturnType<typeof autoDjControllerGetCandidates>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof autoDjControllerGetCandidates>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof autoDjControllerGetCandidates>>,
          TError,
          Awaited<ReturnType<typeof autoDjControllerGetCandidates>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAutoDjControllerGetCandidates<
  TData = Awaited<ReturnType<typeof autoDjControllerGetCandidates>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof autoDjControllerGetCandidates>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof autoDjControllerGetCandidates>>,
          TError,
          Awaited<ReturnType<typeof autoDjControllerGetCandidates>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAutoDjControllerGetCandidates<
  TData = Awaited<ReturnType<typeof autoDjControllerGetCandidates>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof autoDjControllerGetCandidates>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary AutoDJ 후보 조회
 */

export function useAutoDjControllerGetCandidates<
  TData = Awaited<ReturnType<typeof autoDjControllerGetCandidates>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof autoDjControllerGetCandidates>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAutoDjControllerGetCandidatesQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary AutoDJ 풀 새로고침
 */
export const getAutoDjControllerRefreshUrl = (id: string) => {
  return `/api/rooms/${id}/autodj/refresh`;
};

export const autoDjControllerRefresh = async (id: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAutoDjControllerRefreshUrl(id), {
    ...options,
    method: 'POST',
  });
};

export const getAutoDjControllerRefreshMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof autoDjControllerRefresh>>, TError, { id: string }, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof autoDjControllerRefresh>>, TError, { id: string }, TContext> => {
  const mutationKey = ['autoDjControllerRefresh'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof autoDjControllerRefresh>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return autoDjControllerRefresh(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AutoDjControllerRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof autoDjControllerRefresh>>>;

export type AutoDjControllerRefreshMutationError = unknown;

/**
 * @summary AutoDJ 풀 새로고침
 */
export const useAutoDjControllerRefresh = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof autoDjControllerRefresh>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof autoDjControllerRefresh>>, TError, { id: string }, TContext> => {
  const mutationOptions = getAutoDjControllerRefreshMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary AutoDJ 후보 핀 토글
 */
export const getAutoDjControllerPinUrl = (id: string, trackId: string) => {
  return `/api/rooms/${id}/autodj/pin/${trackId}`;
};

export const autoDjControllerPin = async (id: string, trackId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAutoDjControllerPinUrl(id, trackId), {
    ...options,
    method: 'POST',
  });
};

export const getAutoDjControllerPinMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof autoDjControllerPin>>,
    TError,
    { id: string; trackId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof autoDjControllerPin>>,
  TError,
  { id: string; trackId: string },
  TContext
> => {
  const mutationKey = ['autoDjControllerPin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof autoDjControllerPin>>,
    { id: string; trackId: string }
  > = (props) => {
    const { id, trackId } = props ?? {};

    return autoDjControllerPin(id, trackId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AutoDjControllerPinMutationResult = NonNullable<Awaited<ReturnType<typeof autoDjControllerPin>>>;

export type AutoDjControllerPinMutationError = unknown;

/**
 * @summary AutoDJ 후보 핀 토글
 */
export const useAutoDjControllerPin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof autoDjControllerPin>>,
      TError,
      { id: string; trackId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof autoDjControllerPin>>,
  TError,
  { id: string; trackId: string },
  TContext
> => {
  const mutationOptions = getAutoDjControllerPinMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary AutoDJ 후보 스킵
 */
export const getAutoDjControllerSkipUrl = (id: string, trackId: string) => {
  return `/api/rooms/${id}/autodj/skip/${trackId}`;
};

export const autoDjControllerSkip = async (id: string, trackId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAutoDjControllerSkipUrl(id, trackId), {
    ...options,
    method: 'DELETE',
  });
};

export const getAutoDjControllerSkipMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof autoDjControllerSkip>>,
    TError,
    { id: string; trackId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof autoDjControllerSkip>>,
  TError,
  { id: string; trackId: string },
  TContext
> => {
  const mutationKey = ['autoDjControllerSkip'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof autoDjControllerSkip>>,
    { id: string; trackId: string }
  > = (props) => {
    const { id, trackId } = props ?? {};

    return autoDjControllerSkip(id, trackId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AutoDjControllerSkipMutationResult = NonNullable<Awaited<ReturnType<typeof autoDjControllerSkip>>>;

export type AutoDjControllerSkipMutationError = unknown;

/**
 * @summary AutoDJ 후보 스킵
 */
export const useAutoDjControllerSkip = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof autoDjControllerSkip>>,
      TError,
      { id: string; trackId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof autoDjControllerSkip>>,
  TError,
  { id: string; trackId: string },
  TContext
> => {
  const mutationOptions = getAutoDjControllerSkipMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary AutoDJ 후보를 큐에 즉시 추가
 */
export const getAutoDjControllerEnqueueUrl = (id: string, trackId: string) => {
  return `/api/rooms/${id}/autodj/enqueue/${trackId}`;
};

export const autoDjControllerEnqueue = async (id: string, trackId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAutoDjControllerEnqueueUrl(id, trackId), {
    ...options,
    method: 'POST',
  });
};

export const getAutoDjControllerEnqueueMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof autoDjControllerEnqueue>>,
    TError,
    { id: string; trackId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof autoDjControllerEnqueue>>,
  TError,
  { id: string; trackId: string },
  TContext
> => {
  const mutationKey = ['autoDjControllerEnqueue'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof autoDjControllerEnqueue>>,
    { id: string; trackId: string }
  > = (props) => {
    const { id, trackId } = props ?? {};

    return autoDjControllerEnqueue(id, trackId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AutoDjControllerEnqueueMutationResult = NonNullable<Awaited<ReturnType<typeof autoDjControllerEnqueue>>>;

export type AutoDjControllerEnqueueMutationError = unknown;

/**
 * @summary AutoDJ 후보를 큐에 즉시 추가
 */
export const useAutoDjControllerEnqueue = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof autoDjControllerEnqueue>>,
      TError,
      { id: string; trackId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof autoDjControllerEnqueue>>,
  TError,
  { id: string; trackId: string },
  TContext
> => {
  const mutationOptions = getAutoDjControllerEnqueueMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary AutoDJ 일시중지 토글
 */
export const getAutoDjControllerTogglePauseUrl = (id: string) => {
  return `/api/rooms/${id}/autodj/pause`;
};

export const autoDjControllerTogglePause = async (id: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getAutoDjControllerTogglePauseUrl(id), {
    ...options,
    method: 'POST',
  });
};

export const getAutoDjControllerTogglePauseMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof autoDjControllerTogglePause>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof autoDjControllerTogglePause>>, TError, { id: string }, TContext> => {
  const mutationKey = ['autoDjControllerTogglePause'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof autoDjControllerTogglePause>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return autoDjControllerTogglePause(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AutoDjControllerTogglePauseMutationResult = NonNullable<
  Awaited<ReturnType<typeof autoDjControllerTogglePause>>
>;

export type AutoDjControllerTogglePauseMutationError = unknown;

/**
 * @summary AutoDJ 일시중지 토글
 */
export const useAutoDjControllerTogglePause = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof autoDjControllerTogglePause>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof autoDjControllerTogglePause>>, TError, { id: string }, TContext> => {
  const mutationOptions = getAutoDjControllerTogglePauseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
