/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  PlaylistTracksResponse,
  RecommendedResponse,
  SearchControllerGetPlaylistTracksParams,
  SearchControllerSearchParams,
  SearchControllerSuggestParams,
  SearchResponse,
  ShowcaseResponse,
  SuggestResponse,
} from '.././model';

import { customFetch } from '../../lib/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 검색어 자동완성
 */
export const getSearchControllerSuggestUrl = (params: SearchControllerSuggestParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/search/suggest?${stringifiedParams}` : `/api/search/suggest`;
};

export const searchControllerSuggest = async (
  params: SearchControllerSuggestParams,
  options?: RequestInit,
): Promise<SuggestResponse> => {
  return customFetch<SuggestResponse>(getSearchControllerSuggestUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getSearchControllerSuggestQueryKey = (params?: SearchControllerSuggestParams) => {
  return [`/api/search/suggest`, ...(params ? [params] : [])] as const;
};

export const getSearchControllerSuggestQueryOptions = <
  TData = Awaited<ReturnType<typeof searchControllerSuggest>>,
  TError = unknown,
>(
  params: SearchControllerSuggestParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSuggest>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchControllerSuggestQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchControllerSuggest>>> = ({ signal }) =>
    searchControllerSuggest(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchControllerSuggest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchControllerSuggestQueryResult = NonNullable<Awaited<ReturnType<typeof searchControllerSuggest>>>;
export type SearchControllerSuggestQueryError = unknown;

export function useSearchControllerSuggest<
  TData = Awaited<ReturnType<typeof searchControllerSuggest>>,
  TError = unknown,
>(
  params: SearchControllerSuggestParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSuggest>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerSuggest>>,
          TError,
          Awaited<ReturnType<typeof searchControllerSuggest>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchControllerSuggest<
  TData = Awaited<ReturnType<typeof searchControllerSuggest>>,
  TError = unknown,
>(
  params: SearchControllerSuggestParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSuggest>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerSuggest>>,
          TError,
          Awaited<ReturnType<typeof searchControllerSuggest>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchControllerSuggest<
  TData = Awaited<ReturnType<typeof searchControllerSuggest>>,
  TError = unknown,
>(
  params: SearchControllerSuggestParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSuggest>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 검색어 자동완성
 */

export function useSearchControllerSuggest<
  TData = Awaited<ReturnType<typeof searchControllerSuggest>>,
  TError = unknown,
>(
  params: SearchControllerSuggestParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSuggest>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchControllerSuggestQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 곡 + 플레이리스트 검색
 */
export const getSearchControllerSearchUrl = (params?: SearchControllerSearchParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/search?${stringifiedParams}` : `/api/search`;
};

export const searchControllerSearch = async (
  params?: SearchControllerSearchParams,
  options?: RequestInit,
): Promise<SearchResponse> => {
  return customFetch<SearchResponse>(getSearchControllerSearchUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getSearchControllerSearchQueryKey = (params?: SearchControllerSearchParams) => {
  return [`/api/search`, ...(params ? [params] : [])] as const;
};

export const getSearchControllerSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof searchControllerSearch>>,
  TError = unknown,
>(
  params?: SearchControllerSearchParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchControllerSearchQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchControllerSearch>>> = ({ signal }) =>
    searchControllerSearch(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchControllerSearch>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchControllerSearchQueryResult = NonNullable<Awaited<ReturnType<typeof searchControllerSearch>>>;
export type SearchControllerSearchQueryError = unknown;

export function useSearchControllerSearch<TData = Awaited<ReturnType<typeof searchControllerSearch>>, TError = unknown>(
  params: undefined | SearchControllerSearchParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerSearch>>,
          TError,
          Awaited<ReturnType<typeof searchControllerSearch>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchControllerSearch<TData = Awaited<ReturnType<typeof searchControllerSearch>>, TError = unknown>(
  params?: SearchControllerSearchParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerSearch>>,
          TError,
          Awaited<ReturnType<typeof searchControllerSearch>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchControllerSearch<TData = Awaited<ReturnType<typeof searchControllerSearch>>, TError = unknown>(
  params?: SearchControllerSearchParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 곡 + 플레이리스트 검색
 */

export function useSearchControllerSearch<TData = Awaited<ReturnType<typeof searchControllerSearch>>, TError = unknown>(
  params?: SearchControllerSearchParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchControllerSearchQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 쇼케이스 (인기곡/최근/내기록/추천)
 */
export const getSearchControllerGetShowcaseUrl = (roomId: string) => {
  return `/api/search/showcase/${roomId}`;
};

export const searchControllerGetShowcase = async (roomId: string, options?: RequestInit): Promise<ShowcaseResponse> => {
  return customFetch<ShowcaseResponse>(getSearchControllerGetShowcaseUrl(roomId), {
    ...options,
    method: 'GET',
  });
};

export const getSearchControllerGetShowcaseQueryKey = (roomId?: string) => {
  return [`/api/search/showcase/${roomId}`] as const;
};

export const getSearchControllerGetShowcaseQueryOptions = <
  TData = Awaited<ReturnType<typeof searchControllerGetShowcase>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetShowcase>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchControllerGetShowcaseQueryKey(roomId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchControllerGetShowcase>>> = ({ signal }) =>
    searchControllerGetShowcase(roomId, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!roomId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchControllerGetShowcase>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchControllerGetShowcaseQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchControllerGetShowcase>>
>;
export type SearchControllerGetShowcaseQueryError = unknown;

export function useSearchControllerGetShowcase<
  TData = Awaited<ReturnType<typeof searchControllerGetShowcase>>,
  TError = unknown,
>(
  roomId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetShowcase>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerGetShowcase>>,
          TError,
          Awaited<ReturnType<typeof searchControllerGetShowcase>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchControllerGetShowcase<
  TData = Awaited<ReturnType<typeof searchControllerGetShowcase>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetShowcase>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerGetShowcase>>,
          TError,
          Awaited<ReturnType<typeof searchControllerGetShowcase>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchControllerGetShowcase<
  TData = Awaited<ReturnType<typeof searchControllerGetShowcase>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetShowcase>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 쇼케이스 (인기곡/최근/내기록/추천)
 */

export function useSearchControllerGetShowcase<
  TData = Awaited<ReturnType<typeof searchControllerGetShowcase>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetShowcase>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchControllerGetShowcaseQueryOptions(roomId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 추천곡 (YouTube 관련 영상 기반)
 */
export const getSearchControllerGetRecommendedUrl = (roomId: string) => {
  return `/api/search/recommended/${roomId}`;
};

export const searchControllerGetRecommended = async (
  roomId: string,
  options?: RequestInit,
): Promise<RecommendedResponse> => {
  return customFetch<RecommendedResponse>(getSearchControllerGetRecommendedUrl(roomId), {
    ...options,
    method: 'GET',
  });
};

export const getSearchControllerGetRecommendedQueryKey = (roomId?: string) => {
  return [`/api/search/recommended/${roomId}`] as const;
};

export const getSearchControllerGetRecommendedQueryOptions = <
  TData = Awaited<ReturnType<typeof searchControllerGetRecommended>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetRecommended>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchControllerGetRecommendedQueryKey(roomId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchControllerGetRecommended>>> = ({ signal }) =>
    searchControllerGetRecommended(roomId, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!roomId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchControllerGetRecommended>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchControllerGetRecommendedQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchControllerGetRecommended>>
>;
export type SearchControllerGetRecommendedQueryError = unknown;

export function useSearchControllerGetRecommended<
  TData = Awaited<ReturnType<typeof searchControllerGetRecommended>>,
  TError = unknown,
>(
  roomId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetRecommended>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerGetRecommended>>,
          TError,
          Awaited<ReturnType<typeof searchControllerGetRecommended>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchControllerGetRecommended<
  TData = Awaited<ReturnType<typeof searchControllerGetRecommended>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetRecommended>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerGetRecommended>>,
          TError,
          Awaited<ReturnType<typeof searchControllerGetRecommended>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchControllerGetRecommended<
  TData = Awaited<ReturnType<typeof searchControllerGetRecommended>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetRecommended>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 추천곡 (YouTube 관련 영상 기반)
 */

export function useSearchControllerGetRecommended<
  TData = Awaited<ReturnType<typeof searchControllerGetRecommended>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetRecommended>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchControllerGetRecommendedQueryOptions(roomId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 플레이리스트 곡 목록 조회
 */
export const getSearchControllerGetPlaylistTracksUrl = (
  id: string,
  params: SearchControllerGetPlaylistTracksParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/search/playlist/${id}?${stringifiedParams}`
    : `/api/search/playlist/${id}`;
};

export const searchControllerGetPlaylistTracks = async (
  id: string,
  params: SearchControllerGetPlaylistTracksParams,
  options?: RequestInit,
): Promise<PlaylistTracksResponse> => {
  return customFetch<PlaylistTracksResponse>(getSearchControllerGetPlaylistTracksUrl(id, params), {
    ...options,
    method: 'GET',
  });
};

export const getSearchControllerGetPlaylistTracksQueryKey = (
  id?: string,
  params?: SearchControllerGetPlaylistTracksParams,
) => {
  return [`/api/search/playlist/${id}`, ...(params ? [params] : [])] as const;
};

export const getSearchControllerGetPlaylistTracksQueryOptions = <
  TData = Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>,
  TError = unknown,
>(
  id: string,
  params: SearchControllerGetPlaylistTracksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchControllerGetPlaylistTracksQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>> = ({ signal }) =>
    searchControllerGetPlaylistTracks(id, params, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchControllerGetPlaylistTracksQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>
>;
export type SearchControllerGetPlaylistTracksQueryError = unknown;

export function useSearchControllerGetPlaylistTracks<
  TData = Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>,
  TError = unknown,
>(
  id: string,
  params: SearchControllerGetPlaylistTracksParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>,
          TError,
          Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchControllerGetPlaylistTracks<
  TData = Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>,
  TError = unknown,
>(
  id: string,
  params: SearchControllerGetPlaylistTracksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>,
          TError,
          Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSearchControllerGetPlaylistTracks<
  TData = Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>,
  TError = unknown,
>(
  id: string,
  params: SearchControllerGetPlaylistTracksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 플레이리스트 곡 목록 조회
 */

export function useSearchControllerGetPlaylistTracks<
  TData = Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>,
  TError = unknown,
>(
  id: string,
  params: SearchControllerGetPlaylistTracksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetPlaylistTracks>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSearchControllerGetPlaylistTracksQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
