/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { StreamControllerGetStreamToken200 } from '.././model';

import { customFetch } from '.././mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 스트림 전용 토큰 발급 (Cast/AirPlay용)
 */
export const getStreamControllerGetStreamTokenUrl = (id: string) => {
  return `/api/rooms/${id}/stream-token`;
};

export const streamControllerGetStreamToken = async (
  id: string,
  options?: RequestInit,
): Promise<StreamControllerGetStreamToken200> => {
  return customFetch<StreamControllerGetStreamToken200>(getStreamControllerGetStreamTokenUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getStreamControllerGetStreamTokenQueryKey = (id?: string) => {
  return [`/api/rooms/${id}/stream-token`] as const;
};

export const getStreamControllerGetStreamTokenQueryOptions = <
  TData = Awaited<ReturnType<typeof streamControllerGetStreamToken>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof streamControllerGetStreamToken>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getStreamControllerGetStreamTokenQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof streamControllerGetStreamToken>>> = ({ signal }) =>
    streamControllerGetStreamToken(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof streamControllerGetStreamToken>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StreamControllerGetStreamTokenQueryResult = NonNullable<
  Awaited<ReturnType<typeof streamControllerGetStreamToken>>
>;
export type StreamControllerGetStreamTokenQueryError = unknown;

export function useStreamControllerGetStreamToken<
  TData = Awaited<ReturnType<typeof streamControllerGetStreamToken>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof streamControllerGetStreamToken>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamControllerGetStreamToken>>,
          TError,
          Awaited<ReturnType<typeof streamControllerGetStreamToken>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useStreamControllerGetStreamToken<
  TData = Awaited<ReturnType<typeof streamControllerGetStreamToken>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof streamControllerGetStreamToken>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamControllerGetStreamToken>>,
          TError,
          Awaited<ReturnType<typeof streamControllerGetStreamToken>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useStreamControllerGetStreamToken<
  TData = Awaited<ReturnType<typeof streamControllerGetStreamToken>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof streamControllerGetStreamToken>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 스트림 전용 토큰 발급 (Cast/AirPlay용)
 */

export function useStreamControllerGetStreamToken<
  TData = Awaited<ReturnType<typeof streamControllerGetStreamToken>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof streamControllerGetStreamToken>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getStreamControllerGetStreamTokenQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
