/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customFetch } from '../../lib/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary PoW 챌린지 생성
 */
export const getCaptchaControllerGetChallengeUrl = () => {
  return `/api/captcha/challenge`;
};

export const captchaControllerGetChallenge = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getCaptchaControllerGetChallengeUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getCaptchaControllerGetChallengeQueryKey = () => {
  return [`/api/captcha/challenge`] as const;
};

export const getCaptchaControllerGetChallengeQueryOptions = <
  TData = Awaited<ReturnType<typeof captchaControllerGetChallenge>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof captchaControllerGetChallenge>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCaptchaControllerGetChallengeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof captchaControllerGetChallenge>>> = ({ signal }) =>
    captchaControllerGetChallenge({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof captchaControllerGetChallenge>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CaptchaControllerGetChallengeQueryResult = NonNullable<
  Awaited<ReturnType<typeof captchaControllerGetChallenge>>
>;
export type CaptchaControllerGetChallengeQueryError = unknown;

export function useCaptchaControllerGetChallenge<
  TData = Awaited<ReturnType<typeof captchaControllerGetChallenge>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof captchaControllerGetChallenge>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof captchaControllerGetChallenge>>,
          TError,
          Awaited<ReturnType<typeof captchaControllerGetChallenge>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCaptchaControllerGetChallenge<
  TData = Awaited<ReturnType<typeof captchaControllerGetChallenge>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof captchaControllerGetChallenge>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof captchaControllerGetChallenge>>,
          TError,
          Awaited<ReturnType<typeof captchaControllerGetChallenge>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCaptchaControllerGetChallenge<
  TData = Awaited<ReturnType<typeof captchaControllerGetChallenge>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof captchaControllerGetChallenge>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary PoW 챌린지 생성
 */

export function useCaptchaControllerGetChallenge<
  TData = Awaited<ReturnType<typeof captchaControllerGetChallenge>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof captchaControllerGetChallenge>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCaptchaControllerGetChallengeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
