/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { TrackStats, VoteDto, VoteResponse } from '.././model';

import { customFetch } from '../../lib/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 곡 투표 (좋아요/싫어요, 토글)
 */
export const getTracksControllerVoteUrl = (id: string) => {
  return `/api/tracks/${id}/vote`;
};

export const tracksControllerVote = async (
  id: string,
  voteDto: VoteDto,
  options?: RequestInit,
): Promise<VoteResponse> => {
  return customFetch<VoteResponse>(getTracksControllerVoteUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(voteDto),
  });
};

export const getTracksControllerVoteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tracksControllerVote>>,
    TError,
    { id: string; data: VoteDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tracksControllerVote>>,
  TError,
  { id: string; data: VoteDto },
  TContext
> => {
  const mutationKey = ['tracksControllerVote'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tracksControllerVote>>,
    { id: string; data: VoteDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return tracksControllerVote(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TracksControllerVoteMutationResult = NonNullable<Awaited<ReturnType<typeof tracksControllerVote>>>;
export type TracksControllerVoteMutationBody = VoteDto;
export type TracksControllerVoteMutationError = unknown;

/**
 * @summary 곡 투표 (좋아요/싫어요, 토글)
 */
export const useTracksControllerVote = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tracksControllerVote>>,
      TError,
      { id: string; data: VoteDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tracksControllerVote>>,
  TError,
  { id: string; data: VoteDto },
  TContext
> => {
  const mutationOptions = getTracksControllerVoteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 곡 투표 취소
 */
export const getTracksControllerRemoveVoteUrl = (id: string) => {
  return `/api/tracks/${id}/vote`;
};

export const tracksControllerRemoveVote = async (id: string, options?: RequestInit): Promise<VoteResponse> => {
  return customFetch<VoteResponse>(getTracksControllerRemoveVoteUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getTracksControllerRemoveVoteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tracksControllerRemoveVote>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof tracksControllerRemoveVote>>, TError, { id: string }, TContext> => {
  const mutationKey = ['tracksControllerRemoveVote'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof tracksControllerRemoveVote>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return tracksControllerRemoveVote(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TracksControllerRemoveVoteMutationResult = NonNullable<
  Awaited<ReturnType<typeof tracksControllerRemoveVote>>
>;

export type TracksControllerRemoveVoteMutationError = unknown;

/**
 * @summary 곡 투표 취소
 */
export const useTracksControllerRemoveVote = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tracksControllerRemoveVote>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof tracksControllerRemoveVote>>, TError, { id: string }, TContext> => {
  const mutationOptions = getTracksControllerRemoveVoteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 내 투표 상태 조회
 */
export const getTracksControllerGetMyVoteUrl = (id: string) => {
  return `/api/tracks/${id}/vote`;
};

export const tracksControllerGetMyVote = async (id: string, options?: RequestInit): Promise<VoteResponse> => {
  return customFetch<VoteResponse>(getTracksControllerGetMyVoteUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getTracksControllerGetMyVoteQueryKey = (id?: string) => {
  return [`/api/tracks/${id}/vote`] as const;
};

export const getTracksControllerGetMyVoteQueryOptions = <
  TData = Awaited<ReturnType<typeof tracksControllerGetMyVote>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tracksControllerGetMyVote>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTracksControllerGetMyVoteQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof tracksControllerGetMyVote>>> = ({ signal }) =>
    tracksControllerGetMyVote(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tracksControllerGetMyVote>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TracksControllerGetMyVoteQueryResult = NonNullable<Awaited<ReturnType<typeof tracksControllerGetMyVote>>>;
export type TracksControllerGetMyVoteQueryError = unknown;

export function useTracksControllerGetMyVote<
  TData = Awaited<ReturnType<typeof tracksControllerGetMyVote>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof tracksControllerGetMyVote>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tracksControllerGetMyVote>>,
          TError,
          Awaited<ReturnType<typeof tracksControllerGetMyVote>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTracksControllerGetMyVote<
  TData = Awaited<ReturnType<typeof tracksControllerGetMyVote>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tracksControllerGetMyVote>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tracksControllerGetMyVote>>,
          TError,
          Awaited<ReturnType<typeof tracksControllerGetMyVote>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTracksControllerGetMyVote<
  TData = Awaited<ReturnType<typeof tracksControllerGetMyVote>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tracksControllerGetMyVote>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 내 투표 상태 조회
 */

export function useTracksControllerGetMyVote<
  TData = Awaited<ReturnType<typeof tracksControllerGetMyVote>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tracksControllerGetMyVote>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTracksControllerGetMyVoteQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 곡 통계 조회
 */
export const getTracksControllerGetStatsUrl = (id: string) => {
  return `/api/tracks/${id}/stats`;
};

export const tracksControllerGetStats = async (id: string, options?: RequestInit): Promise<TrackStats> => {
  return customFetch<TrackStats>(getTracksControllerGetStatsUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getTracksControllerGetStatsQueryKey = (id?: string) => {
  return [`/api/tracks/${id}/stats`] as const;
};

export const getTracksControllerGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof tracksControllerGetStats>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tracksControllerGetStats>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTracksControllerGetStatsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof tracksControllerGetStats>>> = ({ signal }) =>
    tracksControllerGetStats(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tracksControllerGetStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TracksControllerGetStatsQueryResult = NonNullable<Awaited<ReturnType<typeof tracksControllerGetStats>>>;
export type TracksControllerGetStatsQueryError = unknown;

export function useTracksControllerGetStats<
  TData = Awaited<ReturnType<typeof tracksControllerGetStats>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof tracksControllerGetStats>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tracksControllerGetStats>>,
          TError,
          Awaited<ReturnType<typeof tracksControllerGetStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTracksControllerGetStats<
  TData = Awaited<ReturnType<typeof tracksControllerGetStats>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tracksControllerGetStats>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tracksControllerGetStats>>,
          TError,
          Awaited<ReturnType<typeof tracksControllerGetStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTracksControllerGetStats<
  TData = Awaited<ReturnType<typeof tracksControllerGetStats>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tracksControllerGetStats>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 곡 통계 조회
 */

export function useTracksControllerGetStats<
  TData = Awaited<ReturnType<typeof tracksControllerGetStats>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tracksControllerGetStats>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTracksControllerGetStatsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
