/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { SetupStatusResponse } from '.././model';

import { customFetch } from '.././mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 초기 설정 필요 여부
 */
export const getSetupControllerStatusUrl = () => {
  return `/api/setup/status`;
};

export const setupControllerStatus = async (options?: RequestInit): Promise<SetupStatusResponse> => {
  return customFetch<SetupStatusResponse>(getSetupControllerStatusUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getSetupControllerStatusQueryKey = () => {
  return [`/api/setup/status`] as const;
};

export const getSetupControllerStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof setupControllerStatus>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof setupControllerStatus>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSetupControllerStatusQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof setupControllerStatus>>> = ({ signal }) =>
    setupControllerStatus({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof setupControllerStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SetupControllerStatusQueryResult = NonNullable<Awaited<ReturnType<typeof setupControllerStatus>>>;
export type SetupControllerStatusQueryError = unknown;

export function useSetupControllerStatus<TData = Awaited<ReturnType<typeof setupControllerStatus>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof setupControllerStatus>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof setupControllerStatus>>,
          TError,
          Awaited<ReturnType<typeof setupControllerStatus>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSetupControllerStatus<TData = Awaited<ReturnType<typeof setupControllerStatus>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof setupControllerStatus>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof setupControllerStatus>>,
          TError,
          Awaited<ReturnType<typeof setupControllerStatus>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSetupControllerStatus<TData = Awaited<ReturnType<typeof setupControllerStatus>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof setupControllerStatus>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 초기 설정 필요 여부
 */

export function useSetupControllerStatus<TData = Awaited<ReturnType<typeof setupControllerStatus>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof setupControllerStatus>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSetupControllerStatusQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
