/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

import type { CreateReportDto, Report } from '.././model';

import { customFetch } from '.././mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 신고 접수
 */
export const getReportControllerCreateReportUrl = () => {
  return `/api/reports`;
};

export const reportControllerCreateReport = async (
  createReportDto: CreateReportDto,
  options?: RequestInit,
): Promise<Report> => {
  return customFetch<Report>(getReportControllerCreateReportUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReportDto),
  });
};

export const getReportControllerCreateReportMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reportControllerCreateReport>>,
    TError,
    { data: CreateReportDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reportControllerCreateReport>>,
  TError,
  { data: CreateReportDto },
  TContext
> => {
  const mutationKey = ['reportControllerCreateReport'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reportControllerCreateReport>>,
    { data: CreateReportDto }
  > = (props) => {
    const { data } = props ?? {};

    return reportControllerCreateReport(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReportControllerCreateReportMutationResult = NonNullable<
  Awaited<ReturnType<typeof reportControllerCreateReport>>
>;
export type ReportControllerCreateReportMutationBody = CreateReportDto;
export type ReportControllerCreateReportMutationError = unknown;

/**
 * @summary 신고 접수
 */
export const useReportControllerCreateReport = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reportControllerCreateReport>>,
      TError,
      { data: CreateReportDto },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reportControllerCreateReport>>,
  TError,
  { data: CreateReportDto },
  TContext
> => {
  const mutationOptions = getReportControllerCreateReportMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
