/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AddFavoriteBody, FavoriteIdsResponse, FavoriteItem } from '.././model';

import { customFetch } from '.././mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 내 즐겨찾기 목록
 */
export const getFavoritesControllerListUrl = () => {
  return `/api/favorites`;
};

export const favoritesControllerList = async (options?: RequestInit): Promise<FavoriteItem[]> => {
  return customFetch<FavoriteItem[]>(getFavoritesControllerListUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getFavoritesControllerListQueryKey = () => {
  return [`/api/favorites`] as const;
};

export const getFavoritesControllerListQueryOptions = <
  TData = Awaited<ReturnType<typeof favoritesControllerList>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerList>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFavoritesControllerListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof favoritesControllerList>>> = ({ signal }) =>
    favoritesControllerList({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof favoritesControllerList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FavoritesControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof favoritesControllerList>>>;
export type FavoritesControllerListQueryError = unknown;

export function useFavoritesControllerList<
  TData = Awaited<ReturnType<typeof favoritesControllerList>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerList>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFavoritesControllerList<
  TData = Awaited<ReturnType<typeof favoritesControllerList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerList>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFavoritesControllerList<
  TData = Awaited<ReturnType<typeof favoritesControllerList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerList>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 내 즐겨찾기 목록
 */

export function useFavoritesControllerList<
  TData = Awaited<ReturnType<typeof favoritesControllerList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerList>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFavoritesControllerListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 즐겨찾기 추가
 */
export const getFavoritesControllerAddUrl = () => {
  return `/api/favorites`;
};

export const favoritesControllerAdd = async (
  addFavoriteBody: AddFavoriteBody,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getFavoritesControllerAddUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addFavoriteBody),
  });
};

export const getFavoritesControllerAddMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerAdd>>,
    TError,
    { data: AddFavoriteBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerAdd>>,
  TError,
  { data: AddFavoriteBody },
  TContext
> => {
  const mutationKey = ['favoritesControllerAdd'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof favoritesControllerAdd>>, { data: AddFavoriteBody }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return favoritesControllerAdd(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerAddMutationResult = NonNullable<Awaited<ReturnType<typeof favoritesControllerAdd>>>;
export type FavoritesControllerAddMutationBody = AddFavoriteBody;
export type FavoritesControllerAddMutationError = unknown;

/**
 * @summary 즐겨찾기 추가
 */
export const useFavoritesControllerAdd = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerAdd>>,
      TError,
      { data: AddFavoriteBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof favoritesControllerAdd>>,
  TError,
  { data: AddFavoriteBody },
  TContext
> => {
  const mutationOptions = getFavoritesControllerAddMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 즐겨찾기 sourceId 목록
 */
export const getFavoritesControllerGetIdsUrl = () => {
  return `/api/favorites/ids`;
};

export const favoritesControllerGetIds = async (options?: RequestInit): Promise<FavoriteIdsResponse> => {
  return customFetch<FavoriteIdsResponse>(getFavoritesControllerGetIdsUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getFavoritesControllerGetIdsQueryKey = () => {
  return [`/api/favorites/ids`] as const;
};

export const getFavoritesControllerGetIdsQueryOptions = <
  TData = Awaited<ReturnType<typeof favoritesControllerGetIds>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerGetIds>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFavoritesControllerGetIdsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof favoritesControllerGetIds>>> = ({ signal }) =>
    favoritesControllerGetIds({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof favoritesControllerGetIds>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FavoritesControllerGetIdsQueryResult = NonNullable<Awaited<ReturnType<typeof favoritesControllerGetIds>>>;
export type FavoritesControllerGetIdsQueryError = unknown;

export function useFavoritesControllerGetIds<
  TData = Awaited<ReturnType<typeof favoritesControllerGetIds>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerGetIds>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerGetIds>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerGetIds>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFavoritesControllerGetIds<
  TData = Awaited<ReturnType<typeof favoritesControllerGetIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerGetIds>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerGetIds>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerGetIds>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFavoritesControllerGetIds<
  TData = Awaited<ReturnType<typeof favoritesControllerGetIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerGetIds>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 즐겨찾기 sourceId 목록
 */

export function useFavoritesControllerGetIds<
  TData = Awaited<ReturnType<typeof favoritesControllerGetIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerGetIds>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFavoritesControllerGetIdsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 즐겨찾기 해제
 */
export const getFavoritesControllerRemoveUrl = (sourceId: string) => {
  return `/api/favorites/${sourceId}`;
};

export const favoritesControllerRemove = async (sourceId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getFavoritesControllerRemoveUrl(sourceId), {
    ...options,
    method: 'DELETE',
  });
};

export const getFavoritesControllerRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerRemove>>,
    TError,
    { sourceId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerRemove>>,
  TError,
  { sourceId: string },
  TContext
> => {
  const mutationKey = ['favoritesControllerRemove'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof favoritesControllerRemove>>, { sourceId: string }> = (
    props,
  ) => {
    const { sourceId } = props ?? {};

    return favoritesControllerRemove(sourceId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerRemove>>
>;

export type FavoritesControllerRemoveMutationError = unknown;

/**
 * @summary 즐겨찾기 해제
 */
export const useFavoritesControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerRemove>>,
      TError,
      { sourceId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof favoritesControllerRemove>>, TError, { sourceId: string }, TContext> => {
  const mutationOptions = getFavoritesControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
