/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddFavoriteBody,
  BulkRemoveFavoritesBody,
  CreateFolderBody,
  FavoriteIdsResponse,
  FavoriteItem,
  FolderItem,
  MoveFavoriteBody,
  UpdateFolderBody,
} from '.././model';

import { customFetch } from '.././mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 내 즐겨찾기 목록
 */
export const getFavoritesControllerListUrl = () => {
  return `/api/favorites`;
};

export const favoritesControllerList = async (options?: RequestInit): Promise<FavoriteItem[]> => {
  return customFetch<FavoriteItem[]>(getFavoritesControllerListUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getFavoritesControllerListQueryKey = () => {
  return [`/api/favorites`] as const;
};

export const getFavoritesControllerListQueryOptions = <
  TData = Awaited<ReturnType<typeof favoritesControllerList>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerList>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFavoritesControllerListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof favoritesControllerList>>> = ({ signal }) =>
    favoritesControllerList({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof favoritesControllerList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FavoritesControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof favoritesControllerList>>>;
export type FavoritesControllerListQueryError = unknown;

export function useFavoritesControllerList<
  TData = Awaited<ReturnType<typeof favoritesControllerList>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerList>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFavoritesControllerList<
  TData = Awaited<ReturnType<typeof favoritesControllerList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerList>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFavoritesControllerList<
  TData = Awaited<ReturnType<typeof favoritesControllerList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerList>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 내 즐겨찾기 목록
 */

export function useFavoritesControllerList<
  TData = Awaited<ReturnType<typeof favoritesControllerList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerList>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFavoritesControllerListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 즐겨찾기 추가
 */
export const getFavoritesControllerAddUrl = () => {
  return `/api/favorites`;
};

export const favoritesControllerAdd = async (
  addFavoriteBody: AddFavoriteBody,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getFavoritesControllerAddUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addFavoriteBody),
  });
};

export const getFavoritesControllerAddMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerAdd>>,
    TError,
    { data: AddFavoriteBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerAdd>>,
  TError,
  { data: AddFavoriteBody },
  TContext
> => {
  const mutationKey = ['favoritesControllerAdd'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof favoritesControllerAdd>>, { data: AddFavoriteBody }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return favoritesControllerAdd(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerAddMutationResult = NonNullable<Awaited<ReturnType<typeof favoritesControllerAdd>>>;
export type FavoritesControllerAddMutationBody = AddFavoriteBody;
export type FavoritesControllerAddMutationError = unknown;

/**
 * @summary 즐겨찾기 추가
 */
export const useFavoritesControllerAdd = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerAdd>>,
      TError,
      { data: AddFavoriteBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof favoritesControllerAdd>>,
  TError,
  { data: AddFavoriteBody },
  TContext
> => {
  const mutationOptions = getFavoritesControllerAddMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 즐겨찾기 sourceId 목록
 */
export const getFavoritesControllerGetIdsUrl = () => {
  return `/api/favorites/ids`;
};

export const favoritesControllerGetIds = async (options?: RequestInit): Promise<FavoriteIdsResponse> => {
  return customFetch<FavoriteIdsResponse>(getFavoritesControllerGetIdsUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getFavoritesControllerGetIdsQueryKey = () => {
  return [`/api/favorites/ids`] as const;
};

export const getFavoritesControllerGetIdsQueryOptions = <
  TData = Awaited<ReturnType<typeof favoritesControllerGetIds>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerGetIds>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFavoritesControllerGetIdsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof favoritesControllerGetIds>>> = ({ signal }) =>
    favoritesControllerGetIds({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof favoritesControllerGetIds>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FavoritesControllerGetIdsQueryResult = NonNullable<Awaited<ReturnType<typeof favoritesControllerGetIds>>>;
export type FavoritesControllerGetIdsQueryError = unknown;

export function useFavoritesControllerGetIds<
  TData = Awaited<ReturnType<typeof favoritesControllerGetIds>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerGetIds>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerGetIds>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerGetIds>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFavoritesControllerGetIds<
  TData = Awaited<ReturnType<typeof favoritesControllerGetIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerGetIds>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerGetIds>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerGetIds>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFavoritesControllerGetIds<
  TData = Awaited<ReturnType<typeof favoritesControllerGetIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerGetIds>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 즐겨찾기 sourceId 목록
 */

export function useFavoritesControllerGetIds<
  TData = Awaited<ReturnType<typeof favoritesControllerGetIds>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerGetIds>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFavoritesControllerGetIdsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 즐겨찾기 해제
 */
export const getFavoritesControllerRemoveUrl = (sourceId: string) => {
  return `/api/favorites/${sourceId}`;
};

export const favoritesControllerRemove = async (sourceId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getFavoritesControllerRemoveUrl(sourceId), {
    ...options,
    method: 'DELETE',
  });
};

export const getFavoritesControllerRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerRemove>>,
    TError,
    { sourceId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerRemove>>,
  TError,
  { sourceId: string },
  TContext
> => {
  const mutationKey = ['favoritesControllerRemove'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof favoritesControllerRemove>>, { sourceId: string }> = (
    props,
  ) => {
    const { sourceId } = props ?? {};

    return favoritesControllerRemove(sourceId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerRemove>>
>;

export type FavoritesControllerRemoveMutationError = unknown;

/**
 * @summary 즐겨찾기 해제
 */
export const useFavoritesControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerRemove>>,
      TError,
      { sourceId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof favoritesControllerRemove>>, TError, { sourceId: string }, TContext> => {
  const mutationOptions = getFavoritesControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 즐겨찾기 일괄 해제
 */
export const getFavoritesControllerBulkRemoveUrl = () => {
  return `/api/favorites/bulk-remove`;
};

export const favoritesControllerBulkRemove = async (
  bulkRemoveFavoritesBody: BulkRemoveFavoritesBody,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getFavoritesControllerBulkRemoveUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(bulkRemoveFavoritesBody),
  });
};

export const getFavoritesControllerBulkRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerBulkRemove>>,
    TError,
    { data: BulkRemoveFavoritesBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerBulkRemove>>,
  TError,
  { data: BulkRemoveFavoritesBody },
  TContext
> => {
  const mutationKey = ['favoritesControllerBulkRemove'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof favoritesControllerBulkRemove>>,
    { data: BulkRemoveFavoritesBody }
  > = (props) => {
    const { data } = props ?? {};

    return favoritesControllerBulkRemove(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerBulkRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerBulkRemove>>
>;
export type FavoritesControllerBulkRemoveMutationBody = BulkRemoveFavoritesBody;
export type FavoritesControllerBulkRemoveMutationError = unknown;

/**
 * @summary 즐겨찾기 일괄 해제
 */
export const useFavoritesControllerBulkRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerBulkRemove>>,
      TError,
      { data: BulkRemoveFavoritesBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof favoritesControllerBulkRemove>>,
  TError,
  { data: BulkRemoveFavoritesBody },
  TContext
> => {
  const mutationOptions = getFavoritesControllerBulkRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 폴더 목록
 */
export const getFavoritesControllerListFoldersUrl = () => {
  return `/api/favorites/folders`;
};

export const favoritesControllerListFolders = async (options?: RequestInit): Promise<FolderItem[]> => {
  return customFetch<FolderItem[]>(getFavoritesControllerListFoldersUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getFavoritesControllerListFoldersQueryKey = () => {
  return [`/api/favorites/folders`] as const;
};

export const getFavoritesControllerListFoldersQueryOptions = <
  TData = Awaited<ReturnType<typeof favoritesControllerListFolders>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerListFolders>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFavoritesControllerListFoldersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof favoritesControllerListFolders>>> = ({ signal }) =>
    favoritesControllerListFolders({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof favoritesControllerListFolders>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FavoritesControllerListFoldersQueryResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerListFolders>>
>;
export type FavoritesControllerListFoldersQueryError = unknown;

export function useFavoritesControllerListFolders<
  TData = Awaited<ReturnType<typeof favoritesControllerListFolders>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerListFolders>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerListFolders>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerListFolders>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFavoritesControllerListFolders<
  TData = Awaited<ReturnType<typeof favoritesControllerListFolders>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerListFolders>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof favoritesControllerListFolders>>,
          TError,
          Awaited<ReturnType<typeof favoritesControllerListFolders>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFavoritesControllerListFolders<
  TData = Awaited<ReturnType<typeof favoritesControllerListFolders>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerListFolders>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 폴더 목록
 */

export function useFavoritesControllerListFolders<
  TData = Awaited<ReturnType<typeof favoritesControllerListFolders>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof favoritesControllerListFolders>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFavoritesControllerListFoldersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 폴더 생성
 */
export const getFavoritesControllerCreateFolderUrl = () => {
  return `/api/favorites/folders`;
};

export const favoritesControllerCreateFolder = async (
  createFolderBody: CreateFolderBody,
  options?: RequestInit,
): Promise<FolderItem> => {
  return customFetch<FolderItem>(getFavoritesControllerCreateFolderUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createFolderBody),
  });
};

export const getFavoritesControllerCreateFolderMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerCreateFolder>>,
    TError,
    { data: CreateFolderBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerCreateFolder>>,
  TError,
  { data: CreateFolderBody },
  TContext
> => {
  const mutationKey = ['favoritesControllerCreateFolder'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof favoritesControllerCreateFolder>>,
    { data: CreateFolderBody }
  > = (props) => {
    const { data } = props ?? {};

    return favoritesControllerCreateFolder(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerCreateFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerCreateFolder>>
>;
export type FavoritesControllerCreateFolderMutationBody = CreateFolderBody;
export type FavoritesControllerCreateFolderMutationError = unknown;

/**
 * @summary 폴더 생성
 */
export const useFavoritesControllerCreateFolder = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerCreateFolder>>,
      TError,
      { data: CreateFolderBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof favoritesControllerCreateFolder>>,
  TError,
  { data: CreateFolderBody },
  TContext
> => {
  const mutationOptions = getFavoritesControllerCreateFolderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 폴더 수정
 */
export const getFavoritesControllerUpdateFolderUrl = (id: string) => {
  return `/api/favorites/folders/${id}`;
};

export const favoritesControllerUpdateFolder = async (
  id: string,
  updateFolderBody: UpdateFolderBody,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getFavoritesControllerUpdateFolderUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateFolderBody),
  });
};

export const getFavoritesControllerUpdateFolderMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerUpdateFolder>>,
    TError,
    { id: string; data: UpdateFolderBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerUpdateFolder>>,
  TError,
  { id: string; data: UpdateFolderBody },
  TContext
> => {
  const mutationKey = ['favoritesControllerUpdateFolder'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof favoritesControllerUpdateFolder>>,
    { id: string; data: UpdateFolderBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return favoritesControllerUpdateFolder(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerUpdateFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerUpdateFolder>>
>;
export type FavoritesControllerUpdateFolderMutationBody = UpdateFolderBody;
export type FavoritesControllerUpdateFolderMutationError = unknown;

/**
 * @summary 폴더 수정
 */
export const useFavoritesControllerUpdateFolder = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerUpdateFolder>>,
      TError,
      { id: string; data: UpdateFolderBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof favoritesControllerUpdateFolder>>,
  TError,
  { id: string; data: UpdateFolderBody },
  TContext
> => {
  const mutationOptions = getFavoritesControllerUpdateFolderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 폴더 삭제 (곡 → 미분류)
 */
export const getFavoritesControllerDeleteFolderUrl = (id: string) => {
  return `/api/favorites/folders/${id}`;
};

export const favoritesControllerDeleteFolder = async (id: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getFavoritesControllerDeleteFolderUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getFavoritesControllerDeleteFolderMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerDeleteFolder>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerDeleteFolder>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['favoritesControllerDeleteFolder'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof favoritesControllerDeleteFolder>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return favoritesControllerDeleteFolder(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerDeleteFolderMutationResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerDeleteFolder>>
>;

export type FavoritesControllerDeleteFolderMutationError = unknown;

/**
 * @summary 폴더 삭제 (곡 → 미분류)
 */
export const useFavoritesControllerDeleteFolder = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerDeleteFolder>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof favoritesControllerDeleteFolder>>, TError, { id: string }, TContext> => {
  const mutationOptions = getFavoritesControllerDeleteFolderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 곡 폴더 이동
 */
export const getFavoritesControllerMoveFavoriteUrl = (sourceId: string) => {
  return `/api/favorites/${sourceId}/folder`;
};

export const favoritesControllerMoveFavorite = async (
  sourceId: string,
  moveFavoriteBody: MoveFavoriteBody,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getFavoritesControllerMoveFavoriteUrl(sourceId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(moveFavoriteBody),
  });
};

export const getFavoritesControllerMoveFavoriteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof favoritesControllerMoveFavorite>>,
    TError,
    { sourceId: string; data: MoveFavoriteBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof favoritesControllerMoveFavorite>>,
  TError,
  { sourceId: string; data: MoveFavoriteBody },
  TContext
> => {
  const mutationKey = ['favoritesControllerMoveFavorite'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof favoritesControllerMoveFavorite>>,
    { sourceId: string; data: MoveFavoriteBody }
  > = (props) => {
    const { sourceId, data } = props ?? {};

    return favoritesControllerMoveFavorite(sourceId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FavoritesControllerMoveFavoriteMutationResult = NonNullable<
  Awaited<ReturnType<typeof favoritesControllerMoveFavorite>>
>;
export type FavoritesControllerMoveFavoriteMutationBody = MoveFavoriteBody;
export type FavoritesControllerMoveFavoriteMutationError = unknown;

/**
 * @summary 곡 폴더 이동
 */
export const useFavoritesControllerMoveFavorite = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof favoritesControllerMoveFavorite>>,
      TError,
      { sourceId: string; data: MoveFavoriteBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof favoritesControllerMoveFavorite>>,
  TError,
  { sourceId: string; data: MoveFavoriteBody },
  TContext
> => {
  const mutationOptions = getFavoritesControllerMoveFavoriteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
