/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AddTracksBody, QuotaResponse, ReorderBody, RoomQueue } from '.././model';

import { customFetch } from '../../lib/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 대기열 조회
 */
export const getQueueControllerGetQueueUrl = (roomId: string) => {
  return `/api/queue/${roomId}`;
};

export const queueControllerGetQueue = async (roomId: string, options?: RequestInit): Promise<RoomQueue[]> => {
  return customFetch<RoomQueue[]>(getQueueControllerGetQueueUrl(roomId), {
    ...options,
    method: 'GET',
  });
};

export const getQueueControllerGetQueueQueryKey = (roomId?: string) => {
  return [`/api/queue/${roomId}`] as const;
};

export const getQueueControllerGetQueueQueryOptions = <
  TData = Awaited<ReturnType<typeof queueControllerGetQueue>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetQueue>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getQueueControllerGetQueueQueryKey(roomId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof queueControllerGetQueue>>> = ({ signal }) =>
    queueControllerGetQueue(roomId, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!roomId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof queueControllerGetQueue>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueueControllerGetQueueQueryResult = NonNullable<Awaited<ReturnType<typeof queueControllerGetQueue>>>;
export type QueueControllerGetQueueQueryError = unknown;

export function useQueueControllerGetQueue<
  TData = Awaited<ReturnType<typeof queueControllerGetQueue>>,
  TError = unknown,
>(
  roomId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetQueue>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queueControllerGetQueue>>,
          TError,
          Awaited<ReturnType<typeof queueControllerGetQueue>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQueueControllerGetQueue<
  TData = Awaited<ReturnType<typeof queueControllerGetQueue>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetQueue>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queueControllerGetQueue>>,
          TError,
          Awaited<ReturnType<typeof queueControllerGetQueue>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQueueControllerGetQueue<
  TData = Awaited<ReturnType<typeof queueControllerGetQueue>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetQueue>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 대기열 조회
 */

export function useQueueControllerGetQueue<
  TData = Awaited<ReturnType<typeof queueControllerGetQueue>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetQueue>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getQueueControllerGetQueueQueryOptions(roomId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 곡 추가 (단건/일괄)
 */
export const getQueueControllerAddTracksUrl = (roomId: string) => {
  return `/api/queue/${roomId}`;
};

export const queueControllerAddTracks = async (
  roomId: string,
  addTracksBody: AddTracksBody,
  options?: RequestInit,
): Promise<RoomQueue[]> => {
  return customFetch<RoomQueue[]>(getQueueControllerAddTracksUrl(roomId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addTracksBody),
  });
};

export const getQueueControllerAddTracksMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof queueControllerAddTracks>>,
    TError,
    { roomId: string; data: AddTracksBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof queueControllerAddTracks>>,
  TError,
  { roomId: string; data: AddTracksBody },
  TContext
> => {
  const mutationKey = ['queueControllerAddTracks'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof queueControllerAddTracks>>,
    { roomId: string; data: AddTracksBody }
  > = (props) => {
    const { roomId, data } = props ?? {};

    return queueControllerAddTracks(roomId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type QueueControllerAddTracksMutationResult = NonNullable<Awaited<ReturnType<typeof queueControllerAddTracks>>>;
export type QueueControllerAddTracksMutationBody = AddTracksBody;
export type QueueControllerAddTracksMutationError = unknown;

/**
 * @summary 곡 추가 (단건/일괄)
 */
export const useQueueControllerAddTracks = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof queueControllerAddTracks>>,
      TError,
      { roomId: string; data: AddTracksBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof queueControllerAddTracks>>,
  TError,
  { roomId: string; data: AddTracksBody },
  TContext
> => {
  const mutationOptions = getQueueControllerAddTracksMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 내 곡 신청 쿼터 조회
 */
export const getQueueControllerGetMyQuotaUrl = (roomId: string) => {
  return `/api/queue/${roomId}/my-quota`;
};

export const queueControllerGetMyQuota = async (roomId: string, options?: RequestInit): Promise<QuotaResponse> => {
  return customFetch<QuotaResponse>(getQueueControllerGetMyQuotaUrl(roomId), {
    ...options,
    method: 'GET',
  });
};

export const getQueueControllerGetMyQuotaQueryKey = (roomId?: string) => {
  return [`/api/queue/${roomId}/my-quota`] as const;
};

export const getQueueControllerGetMyQuotaQueryOptions = <
  TData = Awaited<ReturnType<typeof queueControllerGetMyQuota>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetMyQuota>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getQueueControllerGetMyQuotaQueryKey(roomId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof queueControllerGetMyQuota>>> = ({ signal }) =>
    queueControllerGetMyQuota(roomId, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!roomId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof queueControllerGetMyQuota>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueueControllerGetMyQuotaQueryResult = NonNullable<Awaited<ReturnType<typeof queueControllerGetMyQuota>>>;
export type QueueControllerGetMyQuotaQueryError = unknown;

export function useQueueControllerGetMyQuota<
  TData = Awaited<ReturnType<typeof queueControllerGetMyQuota>>,
  TError = unknown,
>(
  roomId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetMyQuota>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queueControllerGetMyQuota>>,
          TError,
          Awaited<ReturnType<typeof queueControllerGetMyQuota>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQueueControllerGetMyQuota<
  TData = Awaited<ReturnType<typeof queueControllerGetMyQuota>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetMyQuota>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queueControllerGetMyQuota>>,
          TError,
          Awaited<ReturnType<typeof queueControllerGetMyQuota>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQueueControllerGetMyQuota<
  TData = Awaited<ReturnType<typeof queueControllerGetMyQuota>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetMyQuota>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 내 곡 신청 쿼터 조회
 */

export function useQueueControllerGetMyQuota<
  TData = Awaited<ReturnType<typeof queueControllerGetMyQuota>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetMyQuota>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getQueueControllerGetMyQuotaQueryOptions(roomId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 재생 기록 조회
 */
export const getQueueControllerGetHistoryUrl = (roomId: string) => {
  return `/api/queue/${roomId}/history`;
};

export const queueControllerGetHistory = async (roomId: string, options?: RequestInit): Promise<RoomQueue[]> => {
  return customFetch<RoomQueue[]>(getQueueControllerGetHistoryUrl(roomId), {
    ...options,
    method: 'GET',
  });
};

export const getQueueControllerGetHistoryQueryKey = (roomId?: string) => {
  return [`/api/queue/${roomId}/history`] as const;
};

export const getQueueControllerGetHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof queueControllerGetHistory>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetHistory>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getQueueControllerGetHistoryQueryKey(roomId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof queueControllerGetHistory>>> = ({ signal }) =>
    queueControllerGetHistory(roomId, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!roomId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof queueControllerGetHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueueControllerGetHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof queueControllerGetHistory>>>;
export type QueueControllerGetHistoryQueryError = unknown;

export function useQueueControllerGetHistory<
  TData = Awaited<ReturnType<typeof queueControllerGetHistory>>,
  TError = unknown,
>(
  roomId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetHistory>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queueControllerGetHistory>>,
          TError,
          Awaited<ReturnType<typeof queueControllerGetHistory>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQueueControllerGetHistory<
  TData = Awaited<ReturnType<typeof queueControllerGetHistory>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetHistory>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queueControllerGetHistory>>,
          TError,
          Awaited<ReturnType<typeof queueControllerGetHistory>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQueueControllerGetHistory<
  TData = Awaited<ReturnType<typeof queueControllerGetHistory>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetHistory>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 재생 기록 조회
 */

export function useQueueControllerGetHistory<
  TData = Awaited<ReturnType<typeof queueControllerGetHistory>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof queueControllerGetHistory>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getQueueControllerGetHistoryQueryOptions(roomId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 곡 삭제
 */
export const getQueueControllerRemoveTrackUrl = (roomId: string, queueId: string) => {
  return `/api/queue/${roomId}/${queueId}`;
};

export const queueControllerRemoveTrack = async (
  roomId: string,
  queueId: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getQueueControllerRemoveTrackUrl(roomId, queueId), {
    ...options,
    method: 'DELETE',
  });
};

export const getQueueControllerRemoveTrackMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof queueControllerRemoveTrack>>,
    TError,
    { roomId: string; queueId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof queueControllerRemoveTrack>>,
  TError,
  { roomId: string; queueId: string },
  TContext
> => {
  const mutationKey = ['queueControllerRemoveTrack'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof queueControllerRemoveTrack>>,
    { roomId: string; queueId: string }
  > = (props) => {
    const { roomId, queueId } = props ?? {};

    return queueControllerRemoveTrack(roomId, queueId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type QueueControllerRemoveTrackMutationResult = NonNullable<
  Awaited<ReturnType<typeof queueControllerRemoveTrack>>
>;

export type QueueControllerRemoveTrackMutationError = unknown;

/**
 * @summary 곡 삭제
 */
export const useQueueControllerRemoveTrack = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof queueControllerRemoveTrack>>,
      TError,
      { roomId: string; queueId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof queueControllerRemoveTrack>>,
  TError,
  { roomId: string; queueId: string },
  TContext
> => {
  const mutationOptions = getQueueControllerRemoveTrackMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 대기열 순서 변경
 */
export const getQueueControllerReorderUrl = (roomId: string) => {
  return `/api/queue/${roomId}/reorder`;
};

export const queueControllerReorder = async (
  roomId: string,
  reorderBody: ReorderBody,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getQueueControllerReorderUrl(roomId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(reorderBody),
  });
};

export const getQueueControllerReorderMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof queueControllerReorder>>,
    TError,
    { roomId: string; data: ReorderBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof queueControllerReorder>>,
  TError,
  { roomId: string; data: ReorderBody },
  TContext
> => {
  const mutationKey = ['queueControllerReorder'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof queueControllerReorder>>,
    { roomId: string; data: ReorderBody }
  > = (props) => {
    const { roomId, data } = props ?? {};

    return queueControllerReorder(roomId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type QueueControllerReorderMutationResult = NonNullable<Awaited<ReturnType<typeof queueControllerReorder>>>;
export type QueueControllerReorderMutationBody = ReorderBody;
export type QueueControllerReorderMutationError = unknown;

/**
 * @summary 대기열 순서 변경
 */
export const useQueueControllerReorder = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof queueControllerReorder>>,
      TError,
      { roomId: string; data: ReorderBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof queueControllerReorder>>,
  TError,
  { roomId: string; data: ReorderBody },
  TContext
> => {
  const mutationOptions = getQueueControllerReorderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
