/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { AddFavoriteBodyProvider } from './addFavoriteBodyProvider';

export interface AddFavoriteBody {
  provider: AddFavoriteBodyProvider;
  sourceId: string;
  name: string;
  artist?: string;
  thumbnail?: string;
  /** @minimum 0 */
  durationMs: number;
}
