/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { AdminRoomItemAutoDjMode } from './adminRoomItemAutoDjMode';

export interface AdminRoomItem {
  id: string;
  host: User;
  /** @nullable */
  hostId?: string | null;
  name: string;
  maxMembers: number;
  isPrivate: boolean;
  /** @nullable */
  password?: string | null;
  inviteCode: string;
  isActive: boolean;
  enqueueWindowMin: number;
  enqueueLimitPerWindow: number;
  crossfade: boolean;
  maxSelectPerAdd: number;
  defaultEnqueueEnabled: boolean;
  defaultVoteSkipEnabled: boolean;
  autoDjEnabled: boolean;
  autoDjMode: AdminRoomItemAutoDjMode;
  autoDjThreshold: number;
  createdAt: string;
  memberCount: number;
}
