/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type AdminRoomItemAutoDjMode = (typeof AdminRoomItemAutoDjMode)[keyof typeof AdminRoomItemAutoDjMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminRoomItemAutoDjMode = {
  related: 'related',
  history: 'history',
  popular: 'popular',
  mixed: 'mixed',
} as const;
