/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type AdminControllerGetReportsStatus =
  (typeof AdminControllerGetReportsStatus)[keyof typeof AdminControllerGetReportsStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminControllerGetReportsStatus = {
  pending: 'pending',
  resolved: 'resolved',
  dismissed: 'dismissed',
} as const;
