/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { AdminRoomItemAutoDjMode } from './adminRoomItemAutoDjMode';

export interface AdminRoomItem {
  id: string;
  host: User;
  /** @nullable */
  hostId?: string | null;
  name: string;
  maxMembers: number;
  isPrivate: boolean;
  /** @nullable */
  password?: string | null;
  inviteCode: string;
  isActive: boolean;
  enqueueWindowMin: number;
  enqueueLimitPerWindow: number;
  crossfade: boolean;
  maxSelectPerAdd: number;
  /** 같은 곡 재신청 쿨다운 (분, 0=제한없음) */
  replayCooldownMin: number;
  defaultEnqueueEnabled: boolean;
  defaultVoteSkipEnabled: boolean;
  autoDjEnabled: boolean;
  autoDjMode: AdminRoomItemAutoDjMode;
  autoDjThreshold: number;
  /**
   * AutoDJ 즐겨찾기 모드 폴더 필터 (null=전체)
   * @nullable
   */
  autoDjFolderId?: string | null;
  /** AutoDJ 즐겨찾기 소진 시 혼합 모드 폴백 */
  autoDjFavFallbackMixed: boolean;
  createdAt: string;
  memberCount: number;
}
