/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { AuditLogItemDetails } from './auditLogItemDetails';

export interface AuditLogItem {
  id: string;
  actorId: string;
  /** @nullable */
  actorNickname: string | null;
  action: string;
  targetType: string;
  /** @nullable */
  targetId: string | null;
  /** @nullable */
  details: AuditLogItemDetails;
  /** @nullable */
  ip: string | null;
  createdAt: string;
}
