/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export interface AutoDjCandidateItem {
  id: string;
  name: string;
  /** @nullable */
  artist: string | null;
  /** @nullable */
  thumbnail: string | null;
  pinned: boolean;
}
