/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export interface ChartTrack {
  id: string;
  /** YouTube video ID */
  sourceId: string;
  title: string;
  artist: string;
  /** 썸네일 URL */
  thumbnail: string;
  /** 출처 플레이리스트 ID */
  playlistId: string;
  /** 장르 (kpop, jpop, pop, hiphop, rock, edm, indie, ballad, anime, game, lofi, citypop, vocaloid) */
  genre: string;
  /**
   * 국가 코드 (KR, JP, US, GLOBAL, null=장르 전용)
   * @nullable
   */
  country?: string | null;
  /** 플레이리스트 내 순위 */
  rank: number;
  /** 마지막 갱신 시각 */
  fetchedAt: string;
}
