/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { TableSizeItem } from './tableSizeItem';

export interface CleanupSummaryResponse {
  totalTracks: number;
  totalPlayHistories: number;
  activeRooms: number;
  inactiveRooms: number;
  totalUsers: number;
  guestUsers: number;
  lyricsFoundTracks: number;
  totalQueueItems: number;
  unplayedTracks: number;
  staleTracksCount: number;
  oldHistories30d: number;
  inactiveRooms7d: number;
  emptyInactiveRooms: number;
  expiredGuests: number;
  inactiveGuests30d: number;
  tableSizes: TableSizeItem[];
}
