/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export interface CreateReportDto {
  targetType: string;
  targetId: string;
  /** @maxLength 500 */
  reason: string;
  /** @maxLength 2000 */
  details?: string;
}
