/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { CreateInviteCodeDtoPermissionsItem } from './createInviteCodeDtoPermissionsItem';

export interface CreateInviteCodeDto {
  /**
   * @minLength 6
   * @maxLength 12
   */
  code?: string;
  /**
   * @minimum 10
   * @maximum 100
   */
  maxUses: number;
  permissions: CreateInviteCodeDtoPermissionsItem[];
  expiresAt?: string;
  allowRegistration?: boolean;
}
