/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { CreateRoomDtoAutoDjMode } from './createRoomDtoAutoDjMode';

export interface CreateRoomDto {
  /**
   * 방 이름
   * @minLength 1
   */
  name: string;
  /**
   * 최대 인원
   * @minimum 2
   * @maximum 50
   */
  maxMembers?: number;
  /** 비공개 여부 */
  isPrivate?: boolean;
  /** 비밀번호 */
  password?: string;
  /**
   * 곡 신청 윈도우(분)
   * @minimum 1
   * @maximum 120
   */
  enqueueWindowMin?: number;
  /**
   * 윈도우당 신청 제한
   * @minimum 1
   * @maximum 100
   */
  enqueueLimitPerWindow?: number;
  /**
   * 한 번에 추가 가능한 곡 수
   * @minimum 1
   * @maximum 10
   */
  maxSelectPerAdd?: number;
  /**
   * 같은 곡 재신청 쿨다운 (분, 0=제한없음)
   * @minimum -1
   * @maximum 1440
   */
  replayCooldownMin?: number;
  /** 곡 전환 크로스페이드 */
  crossfade?: boolean;
  /** 새 멤버 기본 곡 신청 허용 */
  defaultEnqueueEnabled?: boolean;
  /** 새 멤버 기본 스킵 투표 허용 */
  defaultVoteSkipEnabled?: boolean;
  /** AutoDJ 활성화 */
  autoDjEnabled?: boolean;
  /** AutoDJ 모드 */
  autoDjMode?: CreateRoomDtoAutoDjMode;
  /**
   * AutoDJ 트리거 기준 (남은 큐)
   * @minimum 1
   * @maximum 5
   */
  autoDjThreshold?: number;
}
