/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { CreateFolderBodyColor } from './createFolderBodyColor';

export interface CreateFolderBody {
  /**
   * @minLength 2
   * @maxLength 20
   */
  name: string;
  color?: CreateFolderBodyColor;
}
