/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { Provider } from './provider';

export interface FavoriteItem {
  id: string;
  provider: Provider;
  sourceId: string;
  name: string;
  /** @nullable */
  artist?: string | null;
  /** @nullable */
  thumbnail?: string | null;
  durationMs: number;
  /** @nullable */
  folderId?: string | null;
  createdAt: string;
}
