/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export interface GuestLoginDto {
  /** CAPTCHA challenge ID */
  captchaId?: string;
  /** CAPTCHA answer */
  captchaAnswer?: string;
  /**
   * @minLength 6
   * @maxLength 12
   */
  code: string;
  /**
   * @minLength 1
   * @maxLength 30
   */
  nickname: string;
}
