/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { Permission } from './permission';

export interface InviteCode {
  id: string;
  code: string;
  createdBy: User;
  maxUses: number;
  usedCount: number;
  permissions: Permission[];
  /** @nullable */
  expiresAt?: string | null;
  isActive: boolean;
  allowRegistration: boolean;
  createdAt: string;
}
