/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type InviteCodePermissionsItem = (typeof InviteCodePermissionsItem)[keyof typeof InviteCodePermissionsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InviteCodePermissionsItem = {
  Listen: 'Listen',
  Chat: 'Chat',
  Reaction: 'Reaction',
  AddQueue: 'AddQueue',
  VoteSkip: 'VoteSkip',
  CreateRoom: 'CreateRoom',
} as const;
