/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { InviteCodePermissionsItem } from './inviteCodePermissionsItem';

export interface InviteCode {
  id: string;
  code: string;
  createdBy: User;
  maxUses: number;
  usedCount: number;
  permissions: InviteCodePermissionsItem[];
  /** @nullable */
  expiresAt?: string | null;
  isActive: boolean;
  allowRegistration: boolean;
  createdAt: string;
}
