/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export interface LyricsResponse {
  /** @nullable */
  syncedLyrics: string | null;
  /** @nullable */
  lang: string | null;
  /** @nullable */
  ruby: string | null;
  /** @nullable */
  translated: string | null;
  /** @nullable */
  transStatus: string | null;
}
