/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

/**
 * 번역 상태
 */
export type LyricsTransStatus = (typeof LyricsTransStatus)[keyof typeof LyricsTransStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LyricsTransStatus = {
  idle: 'idle',
  pending: 'pending',
  done: 'done',
  failed: 'failed',
} as const;
