/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type MetaStatus = (typeof MetaStatus)[keyof typeof MetaStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MetaStatus = {
  pending: 'pending',
  matched: 'matched',
  notFound: 'notFound',
} as const;
