/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export interface MoveFavoriteBody {
  /**
   * 이동할 폴더 ID (null = 미분류)
   * @nullable
   */
  folderId?: string | null;
}
