/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { MyPermissionsResponsePermissionsItem } from './myPermissionsResponsePermissionsItem';
import type { MyPermissionsResponseAccountPermissionsItem } from './myPermissionsResponseAccountPermissionsItem';
import type { MyPermissionsResponseRoomPermissionsItem } from './myPermissionsResponseRoomPermissionsItem';

export interface MyPermissionsResponse {
  /** 최종 유효 권한 (account ∩ room) */
  permissions: MyPermissionsResponsePermissionsItem[];
  /** 계정 레벨 권한 */
  accountPermissions: MyPermissionsResponseAccountPermissionsItem[];
  /** 방 레벨 권한 */
  roomPermissions: MyPermissionsResponseRoomPermissionsItem[];
}
