/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { Permission } from './permission';

export interface MyPermissionsResponse {
  /** 최종 유효 권한 (account ∩ room) */
  permissions: Permission[];
  /** 계정 레벨 권한 */
  accountPermissions: Permission[];
  /** 방 레벨 권한 */
  roomPermissions: Permission[];
}
