/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type MyPermissionsResponsePermissionsItem =
  (typeof MyPermissionsResponsePermissionsItem)[keyof typeof MyPermissionsResponsePermissionsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MyPermissionsResponsePermissionsItem = {
  listen: 'listen',
  chat: 'chat',
  reaction: 'reaction',
  search: 'search',
  addQueue: 'addQueue',
  voteSkip: 'voteSkip',
  host: 'host',
} as const;
