/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type OptionKey = (typeof OptionKey)[keyof typeof OptionKey];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OptionKey = {
  authguestEnabled: 'auth.guestEnabled',
  authgoogleEnabled: 'auth.googleEnabled',
  authguestMaxAge: 'auth.guestMaxAge',
  captchaenabled: 'captcha.enabled',
  secretgoogleClientId: 'secret.googleClientId',
  secretgoogleClientSecret: 'secret.googleClientSecret',
  secretgoogleCallbackUrl: 'secret.googleCallbackUrl',
  secretgeminiApiKey: 'secret.geminiApiKey',
  roommaxMembers: 'room.maxMembers',
  roommaxRoomsPerUser: 'room.maxRoomsPerUser',
  autodjenabled: 'autodj.enabled',
  queuemaxPerUser: 'queue.maxPerUser',
  queuemaxDuration: 'queue.maxDuration',
  streammaxBitrateEnabled: 'stream.maxBitrateEnabled',
  streammaxBitrate: 'stream.maxBitrate',
  translationenabled: 'translation.enabled',
  translationdailyLimit: 'translation.dailyLimit',
  translationmodel: 'translation.model',
} as const;
