/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { Room } from './room';
import type { PlaybackStatusTrack } from './playbackStatusTrack';
import type { PlaybackStatusStreamState } from './playbackStatusStreamState';

export interface PlaybackStatus {
  roomId: string;
  room: Room;
  /** @nullable */
  track?: PlaybackStatusTrack;
  isPlaying: boolean;
  /** @nullable */
  startedAt?: string | null;
  positionMs: number;
  updatedAt: string;
  /** 경과 시간 (ms) */
  elapsedMs: number;
  /** 스트림 코덱 */
  streamCodec: string;
  /** 스트림 비트레이트 (kbps) */
  streamBitrate: number;
  /** 스트림 상태 */
  streamState: PlaybackStatusStreamState;
}
