/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { LyricsTransStatus } from './lyricsTransStatus';

/**
 * 번역 상태
 * @nullable
 */
export type PlaybackStatusTransStatus = LyricsTransStatus | null;
