/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface PushSettings {
  userId: string;
  trackChanged: boolean;
  voteSkip: boolean;
  hostChanged: boolean;
  mention: boolean;
  user: User;
}
