/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type PushEvent = (typeof PushEvent)[keyof typeof PushEvent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PushEvent = {
  trackChanged: 'trackChanged',
  voteSkipPassed: 'voteSkipPassed',
  hostChanged: 'hostChanged',
  kicked: 'kicked',
  mention: 'mention',
} as const;
