/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export interface QuotaResponse {
  used: number;
  limit: number;
  windowMin: number;
  unlimited: boolean;
  banned: boolean;
  /** 신청 불가 sourceId 목록 (큐 + 현재재생 + 쿨다운) */
  blockedSourceIds: string[];
}
