/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** CAPTCHA challenge ID */
  captchaId?: string;
  /** CAPTCHA answer */
  captchaAnswer?: string;
  /** 초대코드 (첫 유저는 생략 가능) */
  code?: string;
  /**
   * 아이디 (영소문자, 숫자, 언더스코어)
   * @minLength 4
   * @maxLength 20
   * @pattern /^[a-z0-9_]+$/
   */
  username: string;
  /**
   * 비밀번호
   * @minLength 8
   * @maxLength 72
   */
  password: string;
  /**
   * 닉네임
   * @minLength 2
   * @maxLength 20
   */
  nickname: string;
}
