/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type ReportStatusProperty = (typeof ReportStatusProperty)[keyof typeof ReportStatusProperty];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportStatusProperty = {
  pending: 'pending',
  resolved: 'resolved',
  dismissed: 'dismissed',
} as const;
