/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { ReportResolver } from './reportResolver';

export interface Report {
  id: string;
  reporterId: string;
  targetType: string;
  targetId: string;
  reason: string;
  /** @nullable */
  details: string | null;
  status: string;
  /** @nullable */
  resolvedBy: string | null;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  reporter: User;
  /** @nullable */
  resolver: ReportResolver;
}
