/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { AutoDjMode } from './autoDjMode';
import type { RoomDetailAutoDjTags } from './roomDetailAutoDjTags';
import type { MemberWithPermission } from './memberWithPermission';
import type { RoomDetailPlayback } from './roomDetailPlayback';

export interface RoomDetail {
  id: string;
  host: User;
  /** @nullable */
  hostId?: string | null;
  name: string;
  maxMembers: number;
  isPrivate: boolean;
  /** @nullable */
  password?: string | null;
  inviteCode: string;
  isActive: boolean;
  enqueueWindowMin: number;
  enqueueLimitPerWindow: number;
  crossfade: boolean;
  maxSelectPerAdd: number;
  /** 같은 곡 재신청 쿨다운 (분, 0=제한없음) */
  replayCooldownMin: number;
  defaultEnqueueEnabled: boolean;
  defaultVoteSkipEnabled: boolean;
  autoDjEnabled: boolean;
  autoDjMode: AutoDjMode;
  autoDjThreshold: number;
  /**
   * AutoDJ 즐겨찾기 모드 폴더 필터 (null=전체)
   * @nullable
   */
  autoDjFolderId?: string | null;
  /** AutoDJ 즐겨찾기 소진 시 혼합 모드 폴백 */
  autoDjFavFallbackMixed: boolean;
  /**
   * AI DJ 태그 (mood/genre/era/country)
   * @nullable
   */
  autoDjTags?: RoomDetailAutoDjTags;
  /**
   * AI DJ 직접 입력 프롬프트
   * @nullable
   */
  autoDjPrompt?: string | null;
  /** AutoDJ 일시중지 */
  autoDjPaused: boolean;
  createdAt: string;
  members: MemberWithPermission[];
  /** @nullable */
  playback: RoomDetailPlayback;
}
