/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type RoomDetailAutoDjMode = (typeof RoomDetailAutoDjMode)[keyof typeof RoomDetailAutoDjMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoomDetailAutoDjMode = {
  related: 'related',
  history: 'history',
  popular: 'popular',
  mixed: 'mixed',
  favorites: 'favorites',
} as const;
