/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { Room } from './room';
import type { User } from './user';
import type { Permission } from './permission';

export interface RoomPermission {
  roomId: string;
  userId: string;
  room: Room;
  user: User;
  permissions: Permission[];
}
