/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { Room } from './room';
import type { RoomPlaybackTrack } from './roomPlaybackTrack';

export interface RoomPlayback {
  roomId: string;
  room: Room;
  /** @nullable */
  track?: RoomPlaybackTrack;
  isPlaying: boolean;
  /** @nullable */
  startedAt?: string | null;
  positionMs: number;
  updatedAt: string;
}
