/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { Room } from './room';
import type { Track } from './track';
import type { RoomQueueAddedBy } from './roomQueueAddedBy';

export interface RoomQueue {
  id: string;
  room: Room;
  track: Track;
  /** @nullable */
  addedBy?: RoomQueueAddedBy;
  position: number;
  played: boolean;
  isAutoDj: boolean;
  addedAt: string;
  version: number;
}
