/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { SearchResultItemProvider } from './searchResultItemProvider';

export interface SearchResultItem {
  provider: SearchResultItemProvider;
  sourceId: string;
  name: string;
  /** @nullable */
  artist: string | null;
  /** @nullable */
  thumbnail: string | null;
  durationMs: number;
  isOfficial?: boolean;
  views?: number;
}
