/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { WsEvent } from './wsEvent';
import type { AutoDjStatus } from './autoDjStatus';
import type { Language } from './language';
import type { AuthProvider } from './authProvider';
import type { SystemChatEvent } from './systemChatEvent';
import type { OptionKey } from './optionKey';
import type { MetaStatus } from './metaStatus';
import type { PushEvent } from './pushEvent';
import type { TranslationLang } from './translationLang';
import type { LyricsStatus } from './lyricsStatus';
import type { LyricsType } from './lyricsType';
import type { StreamState } from './streamState';
import type { LyricsTransStatus } from './lyricsTransStatus';
import type { ReportStatus } from './reportStatus';

export interface SharedEnums {
  wsEvent: WsEvent;
  autoDjStatus: AutoDjStatus;
  language: Language;
  authProvider: AuthProvider;
  systemChatEvent: SystemChatEvent;
  optionKey: OptionKey;
  metaStatus: MetaStatus;
  pushEvent: PushEvent;
  translationLang: TranslationLang;
  lyricsStatus: LyricsStatus;
  lyricsType: LyricsType;
  streamState: StreamState;
  lyricsTransStatus: LyricsTransStatus;
  reportStatus: ReportStatus;
}
