/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { WsEvent } from './wsEvent';
import type { AutoDjStatus } from './autoDjStatus';
import type { Language } from './language';
import type { AuthProvider } from './authProvider';

export interface SharedEnums {
  wsEvent: WsEvent;
  autoDjStatus: AutoDjStatus;
  language: Language;
  authProvider: AuthProvider;
}
