/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

/**
 * 스트림 상태
 */
export type StreamState = (typeof StreamState)[keyof typeof StreamState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StreamState = {
  idle: 'idle',
  preparing: 'preparing',
  skipping: 'skipping',
  streaming: 'streaming',
} as const;
