/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type SystemChatEvent = (typeof SystemChatEvent)[keyof typeof SystemChatEvent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SystemChatEvent = {
  userJoined: 'userJoined',
  userLeft: 'userLeft',
  userKicked: 'userKicked',
  hostChanged: 'hostChanged',
  trackSkipped: 'trackSkipped',
  trackPrevious: 'trackPrevious',
  trackAdded: 'trackAdded',
  trackUnavailable: 'trackUnavailable',
  voteSkipPassed: 'voteSkipPassed',
  roomClosed: 'roomClosed',
  autoDjEnabled: 'autoDjEnabled',
  autoDjDisabled: 'autoDjDisabled',
  enqueueCountsReset: 'enqueueCountsReset',
} as const;
