/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export interface SystemStatsResponse {
  /** Active ffmpeg processes */
  ffmpegProcesses: number;
  /** Preload buffer memory (MB) */
  preloadMemoryMB: number;
  /** V8 heap used (MB) */
  heapUsedMB: number;
  /** V8 heap total (MB) */
  heapTotalMB: number;
  /** Resident set size (MB) */
  rssMB: number;
  /** Server uptime (seconds) */
  uptimeSec: number;
}
