/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { SystemChatEvent } from './systemChatEvent';

export interface SystemChatMessage {
  event: SystemChatEvent;
  /** 이벤트 관련 닉네임 (입장/퇴장/스킵 등) */
  nickname?: string;
  /** 이벤트 관련 트랙명 (AutoDJ 추가/재생 불가 등) */
  trackName?: string;
  /** 추가된 곡 수 */
  count?: number;
}
