/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { TagPresetItemDto } from './tagPresetItemDto';

export interface TagPresetsDto {
  mood: TagPresetItemDto[];
  genre: TagPresetItemDto[];
  era: TagPresetItemDto[];
  country: TagPresetItemDto[];
}
