/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { TrackMetaStatus } from './trackMetaStatus';
import type { TrackLyricsStatus } from './trackLyricsStatus';

export interface Track {
  id: string;
  youtubeId: string;
  name: string;
  /** @nullable */
  artist?: string | null;
  /** @nullable */
  album?: string | null;
  /** @nullable */
  thumbnail?: string | null;
  /** @nullable */
  songTitle?: string | null;
  /** @nullable */
  songArtist?: string | null;
  /** @nullable */
  songAlbum?: string | null;
  durationMs: number;
  /** @nullable */
  codec?: string | null;
  /** @nullable */
  bitrateKbps?: number | null;
  metaStatus: TrackMetaStatus;
  lyricsStatus: TrackLyricsStatus;
  fetchedAt: string;
  /** @nullable */
  lyricsData: string | null;
  /** @nullable */
  lyricsLang: string | null;
  /** @nullable */
  lyricsRuby: string | null;
  /** @nullable */
  lyricsTranslated: string | null;
  /** @nullable */
  lyricsTransStatus: string | null;
}
