/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type TrackLyricsTransStatus = (typeof TrackLyricsTransStatus)[keyof typeof TrackLyricsTransStatus] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TrackLyricsTransStatus = {
  idle: 'idle',
  pending: 'pending',
  done: 'done',
  failed: 'failed',
} as const;
