/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { Track } from './track';

export interface TrackStats {
  trackId: string;
  totalPlays: number;
  uniqueUsers: number;
  likes: number;
  dislikes: number;
  completedCount: number;
  /** 인기 점수 (시간 감쇠 적용) */
  score: number;
  firstPlayedAt: string;
  lastPlayedAt: string;
  track: Track;
}
