/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type TrackRankingTrackInfoLyricsType =
  | (typeof TrackRankingTrackInfoLyricsType)[keyof typeof TrackRankingTrackInfoLyricsType]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TrackRankingTrackInfoLyricsType = {
  synced: 'synced',
  karaoke: 'karaoke',
} as const;
