/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { TrackRankingTrackInfo } from './trackRankingTrackInfo';

export interface TrackRankingItem {
  trackId: string;
  totalPlays: number;
  uniqueUsers: number;
  likes: number;
  dislikes: number;
  score: number;
  track: TrackRankingTrackInfo;
}
