/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { TrackRankingTrackInfoLyricsStatus } from './trackRankingTrackInfoLyricsStatus';
import type { TrackRankingTrackInfoMetaStatus } from './trackRankingTrackInfoMetaStatus';

export interface TrackRankingTrackInfo {
  name: string;
  sourceId: string;
  /** @nullable */
  songArtist?: string | null;
  lyricsStatus: TrackRankingTrackInfoLyricsStatus;
  /** @nullable */
  lyricsLang?: string | null;
  metaStatus: TrackRankingTrackInfoMetaStatus;
}
