/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { TrackRankingTrackInfoLyricsStatus } from './trackRankingTrackInfoLyricsStatus';
import type { MetaStatus } from './metaStatus';
import type { TrackRankingTrackInfoLyricsType } from './trackRankingTrackInfoLyricsType';

export interface TrackRankingTrackInfo {
  name: string;
  sourceId: string;
  /** @nullable */
  artist?: string | null;
  /** @nullable */
  songTitle?: string | null;
  /** @nullable */
  songArtist?: string | null;
  /** @nullable */
  songAlbum?: string | null;
  lyricsStatus: TrackRankingTrackInfoLyricsStatus;
  /** @nullable */
  lyricsLang?: string | null;
  metaStatus: MetaStatus;
  /** @nullable */
  lyricsType?: TrackRankingTrackInfoLyricsType;
  /** 번역 가사 존재 여부 */
  hasTranslation: boolean;
}
