/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { TrackSourceProvider } from './trackSourceProvider';

export interface TrackSource {
  provider: TrackSourceProvider;
  sourceId: string;
  name: string;
  artist?: string;
  thumbnail?: string;
  durationMs: number;
}
