/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type TranslationLang = (typeof TranslationLang)[keyof typeof TranslationLang];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TranslationLang = {
  ko: 'ko',
  en: 'en',
  ja: 'ja',
  zh: 'zh',
  'zh-TW': 'zh-TW',
  es: 'es',
  fr: 'fr',
  de: 'de',
  pt: 'pt',
  th: 'th',
  vi: 'vi',
  id: 'id',
} as const;
