/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

/**
 * AutoDJ 모드
 */
export type UpdateRoomDtoAutoDjMode = (typeof UpdateRoomDtoAutoDjMode)[keyof typeof UpdateRoomDtoAutoDjMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoomDtoAutoDjMode = {
  related: 'related',
  history: 'history',
  popular: 'popular',
  mixed: 'mixed',
} as const;
