/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type UpdatePermissionsBodyPermissionsItem =
  (typeof UpdatePermissionsBodyPermissionsItem)[keyof typeof UpdatePermissionsBodyPermissionsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePermissionsBodyPermissionsItem = {
  listen: 'listen',
  chat: 'chat',
  reaction: 'reaction',
  search: 'search',
  addQueue: 'addQueue',
  reorder: 'reorder',
  voteSkip: 'voteSkip',
  kick: 'kick',
  createRoom: 'createRoom',
} as const;
