/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type UpdateFolderBodyColor = (typeof UpdateFolderBodyColor)[keyof typeof UpdateFolderBodyColor];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateFolderBodyColor = {
  red: 'red',
  orange: 'orange',
  amber: 'amber',
  yellow: 'yellow',
  lime: 'lime',
  green: 'green',
  emerald: 'emerald',
  teal: 'teal',
  cyan: 'cyan',
  sky: 'sky',
  blue: 'blue',
  indigo: 'indigo',
  violet: 'violet',
  purple: 'purple',
  pink: 'pink',
} as const;
