/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type UserRoleProperty = (typeof UserRoleProperty)[keyof typeof UserRoleProperty];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRoleProperty = {
  user: 'user',
  admin: 'admin',
  superAdmin: 'superAdmin',
  guest: 'guest',
} as const;
