/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { UserDetailResponseRole } from './userDetailResponseRole';
import type { UserDetailResponseProvider } from './userDetailResponseProvider';
import type { UserDetailResponseAccountPermissionsItem } from './userDetailResponseAccountPermissionsItem';
import type { RecentTrackItem } from './recentTrackItem';

export interface UserDetailResponse {
  id: string;
  nickname: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  email?: string | null;
  role: UserDetailResponseRole;
  provider: UserDetailResponseProvider;
  /** @nullable */
  googleId?: string | null;
  /** @nullable */
  bannedAt?: string | null;
  accountPermissions: UserDetailResponseAccountPermissionsItem[];
  createdAt: string;
  roomCount: number;
  totalPlays: number;
  recentTracks: RecentTrackItem[];
}
