/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { UserRole } from './userRole';
import type { AuthProvider } from './authProvider';
import type { Permission } from './permission';
import type { RecentTrackItem } from './recentTrackItem';

export interface UserDetailResponse {
  id: string;
  nickname: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  email?: string | null;
  role: UserRole;
  provider: AuthProvider;
  /** @nullable */
  googleId?: string | null;
  /** @nullable */
  bannedAt?: string | null;
  accountPermissions: Permission[];
  createdAt: string;
  roomCount: number;
  totalPlays: number;
  recentTracks: RecentTrackItem[];
}
