/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { UserProvider } from './userProvider';
import type { UserRole } from './userRole';
import type { UserInviteCode } from './userInviteCode';
import type { UserAccountPermissionsItem } from './userAccountPermissionsItem';

export interface User {
  id: string;
  provider: UserProvider;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  googleId?: string | null;
  /** @nullable */
  email?: string | null;
  nickname: string;
  /** @nullable */
  avatarUrl?: string | null;
  role: UserRole;
  /** @nullable */
  inviteCode?: UserInviteCode;
  accountPermissions: UserAccountPermissionsItem[];
  /** @nullable */
  bannedAt?: string | null;
  createdAt: string;
  /** @nullable */
  passwordHash: string | null;
}
