/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { AuthProvider } from './authProvider';
import type { UserRole } from './userRole';
import type { UserInviteCode } from './userInviteCode';
import type { Permission } from './permission';

export interface User {
  id: string;
  provider: AuthProvider;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  googleId?: string | null;
  /** @nullable */
  email?: string | null;
  nickname: string;
  /** @nullable */
  avatarUrl?: string | null;
  role: UserRole;
  /** @nullable */
  inviteCode?: UserInviteCode;
  accountPermissions: Permission[];
  /** @nullable */
  bannedAt?: string | null;
  createdAt: string;
  /** @nullable */
  passwordHash: string | null;
}
