/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type UserDetailResponseRole = (typeof UserDetailResponseRole)[keyof typeof UserDetailResponseRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDetailResponseRole = {
  user: 'user',
  admin: 'admin',
  superAdmin: 'superAdmin',
  guest: 'guest',
} as const;
