/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { VoteDtoVote } from './voteDtoVote';

export interface VoteDto {
  /** +1 좋아요, -1 싫어요 */
  vote: VoteDtoVote;
  /** 현재 방 ID (WS 브로드캐스트용) */
  roomId: string;
}
