/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export interface VoteResponse {
  /** 현재 투표 상태 (1, -1, 0=취소) */
  vote: number;
  /** 총 좋아요 수 */
  likes: number;
  /** 총 싫어요 수 */
  dislikes: number;
}
