/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

/**
 * +1 좋아요, -1 싫어요
 */
export type VoteDtoVote = (typeof VoteDtoVote)[keyof typeof VoteDtoVote];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoteDtoVote = {
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
} as const;
