/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

/**
 * AutoDJ 상태
 */
export type WsEnumsSchemaAutoDjStatus = (typeof WsEnumsSchemaAutoDjStatus)[keyof typeof WsEnumsSchemaAutoDjStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WsEnumsSchemaAutoDjStatus = {
  idle: 'idle',
  thinking: 'thinking',
  adding: 'adding',
} as const;
