/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

/**
 * WebSocket system event name
 */
export type WsEnumsSchemaWsEvent = (typeof WsEnumsSchemaWsEvent)[keyof typeof WsEnumsSchemaWsEvent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WsEnumsSchemaWsEvent = {
  roomClosed: 'roomClosed',
  roomUpdated: 'roomUpdated',
  userJoined: 'userJoined',
  userLeft: 'userLeft',
  userKicked: 'userKicked',
  hostChanged: 'hostChanged',
  permissionChanged: 'permissionChanged',
  listenerCount: 'listenerCount',
  playbackUpdated: 'playbackUpdated',
  metadataUpdated: 'metadataUpdated',
  trackSkipped: 'trackSkipped',
  trackPrevious: 'trackPrevious',
  trackAdded: 'trackAdded',
  queueUpdated: 'queueUpdated',
  voteSkipRequested: 'voteSkipRequested',
  voteSkipPassed: 'voteSkipPassed',
  voteUpdated: 'voteUpdated',
  trackVote: 'trackVote',
  lyricsResult: 'lyricsResult',
  lyricsUpdated: 'lyricsUpdated',
  autoDjStatus: 'autoDjStatus',
  systemMessage: 'systemMessage',
  enqueueCountsReset: 'enqueueCountsReset',
  chatHistory: 'chatHistory',
  chatMuted: 'chatMuted',
} as const;
