/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

/**
 * 지원 언어
 */
export type WsEnumsSchemaLanguage = (typeof WsEnumsSchemaLanguage)[keyof typeof WsEnumsSchemaLanguage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WsEnumsSchemaLanguage = {
  ko: 'ko',
  en: 'en',
} as const;
