/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { WsEnumsSchemaWsEvent } from './wsEnumsSchemaWsEvent';
import type { WsEnumsSchemaAutoDjStatus } from './wsEnumsSchemaAutoDjStatus';
import type { WsEnumsSchemaLanguage } from './wsEnumsSchemaLanguage';

export interface WsEnumsSchema {
  /** WebSocket system event name */
  wsEvent: WsEnumsSchemaWsEvent;
  /** AutoDJ 상태 */
  autoDjStatus: WsEnumsSchemaAutoDjStatus;
  /** 지원 언어 */
  language: WsEnumsSchemaLanguage;
}
