/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */

export type WsLyricsResultPayloadStatus =
  (typeof WsLyricsResultPayloadStatus)[keyof typeof WsLyricsResultPayloadStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WsLyricsResultPayloadStatus = {
  found: 'found',
  notFound: 'notFound',
  searching: 'searching',
} as const;
