/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import type { WsPlaybackUpdatedPayloadStreamState } from './wsPlaybackUpdatedPayloadStreamState';

export interface WsPlaybackUpdatedPayload {
  /** 현재 트랙 ID */
  trackId?: string;
  /** 경과 시간 (ms) */
  elapsedMs?: number;
  /** 재생 중 여부 */
  isPlaying?: boolean;
  /** 스트림 상태 */
  streamState?: WsPlaybackUpdatedPayloadStreamState;
}
