/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ShareAux API
 * 실시간 음악 공유 플랫폼 API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  LyricsResponse,
  PlaybackStatus,
  PlayerControllerPlayBody,
  RoomPlayback,
  VoteSkipResponse,
} from '.././model';

import { customFetch } from '../../lib/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 트랙 재생
 */
export const getPlayerControllerPlayUrl = (roomId: string) => {
  return `/api/player/${roomId}/play`;
};

export const playerControllerPlay = async (
  roomId: string,
  playerControllerPlayBody: PlayerControllerPlayBody,
  options?: RequestInit,
): Promise<RoomPlayback> => {
  return customFetch<RoomPlayback>(getPlayerControllerPlayUrl(roomId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(playerControllerPlayBody),
  });
};

export const getPlayerControllerPlayMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof playerControllerPlay>>,
    TError,
    { roomId: string; data: PlayerControllerPlayBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof playerControllerPlay>>,
  TError,
  { roomId: string; data: PlayerControllerPlayBody },
  TContext
> => {
  const mutationKey = ['playerControllerPlay'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof playerControllerPlay>>,
    { roomId: string; data: PlayerControllerPlayBody }
  > = (props) => {
    const { roomId, data } = props ?? {};

    return playerControllerPlay(roomId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlayerControllerPlayMutationResult = NonNullable<Awaited<ReturnType<typeof playerControllerPlay>>>;
export type PlayerControllerPlayMutationBody = PlayerControllerPlayBody;
export type PlayerControllerPlayMutationError = unknown;

/**
 * @summary 트랙 재생
 */
export const usePlayerControllerPlay = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playerControllerPlay>>,
      TError,
      { roomId: string; data: PlayerControllerPlayBody },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof playerControllerPlay>>,
  TError,
  { roomId: string; data: PlayerControllerPlayBody },
  TContext
> => {
  const mutationOptions = getPlayerControllerPlayMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 일시정지
 */
export const getPlayerControllerPauseUrl = (roomId: string) => {
  return `/api/player/${roomId}/pause`;
};

export const playerControllerPause = async (roomId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getPlayerControllerPauseUrl(roomId), {
    ...options,
    method: 'PUT',
  });
};

export const getPlayerControllerPauseMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof playerControllerPause>>,
    TError,
    { roomId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof playerControllerPause>>, TError, { roomId: string }, TContext> => {
  const mutationKey = ['playerControllerPause'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof playerControllerPause>>, { roomId: string }> = (
    props,
  ) => {
    const { roomId } = props ?? {};

    return playerControllerPause(roomId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlayerControllerPauseMutationResult = NonNullable<Awaited<ReturnType<typeof playerControllerPause>>>;

export type PlayerControllerPauseMutationError = unknown;

/**
 * @summary 일시정지
 */
export const usePlayerControllerPause = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playerControllerPause>>,
      TError,
      { roomId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof playerControllerPause>>, TError, { roomId: string }, TContext> => {
  const mutationOptions = getPlayerControllerPauseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 재생 재개
 */
export const getPlayerControllerResumeUrl = (roomId: string) => {
  return `/api/player/${roomId}/resume`;
};

export const playerControllerResume = async (roomId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getPlayerControllerResumeUrl(roomId), {
    ...options,
    method: 'PUT',
  });
};

export const getPlayerControllerResumeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof playerControllerResume>>,
    TError,
    { roomId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof playerControllerResume>>, TError, { roomId: string }, TContext> => {
  const mutationKey = ['playerControllerResume'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof playerControllerResume>>, { roomId: string }> = (
    props,
  ) => {
    const { roomId } = props ?? {};

    return playerControllerResume(roomId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlayerControllerResumeMutationResult = NonNullable<Awaited<ReturnType<typeof playerControllerResume>>>;

export type PlayerControllerResumeMutationError = unknown;

/**
 * @summary 재생 재개
 */
export const usePlayerControllerResume = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playerControllerResume>>,
      TError,
      { roomId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof playerControllerResume>>, TError, { roomId: string }, TContext> => {
  const mutationOptions = getPlayerControllerResumeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 다음 곡
 */
export const getPlayerControllerSkipUrl = (roomId: string) => {
  return `/api/player/${roomId}/skip`;
};

export const playerControllerSkip = async (roomId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getPlayerControllerSkipUrl(roomId), {
    ...options,
    method: 'PUT',
  });
};

export const getPlayerControllerSkipMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof playerControllerSkip>>, TError, { roomId: string }, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof playerControllerSkip>>, TError, { roomId: string }, TContext> => {
  const mutationKey = ['playerControllerSkip'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof playerControllerSkip>>, { roomId: string }> = (
    props,
  ) => {
    const { roomId } = props ?? {};

    return playerControllerSkip(roomId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlayerControllerSkipMutationResult = NonNullable<Awaited<ReturnType<typeof playerControllerSkip>>>;

export type PlayerControllerSkipMutationError = unknown;

/**
 * @summary 다음 곡
 */
export const usePlayerControllerSkip = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playerControllerSkip>>,
      TError,
      { roomId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof playerControllerSkip>>, TError, { roomId: string }, TContext> => {
  const mutationOptions = getPlayerControllerSkipMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 이전 곡
 */
export const getPlayerControllerPreviousUrl = (roomId: string) => {
  return `/api/player/${roomId}/previous`;
};

export const playerControllerPrevious = async (roomId: string, options?: RequestInit): Promise<void> => {
  return customFetch<void>(getPlayerControllerPreviousUrl(roomId), {
    ...options,
    method: 'PUT',
  });
};

export const getPlayerControllerPreviousMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof playerControllerPrevious>>,
    TError,
    { roomId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof playerControllerPrevious>>, TError, { roomId: string }, TContext> => {
  const mutationKey = ['playerControllerPrevious'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof playerControllerPrevious>>, { roomId: string }> = (
    props,
  ) => {
    const { roomId } = props ?? {};

    return playerControllerPrevious(roomId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlayerControllerPreviousMutationResult = NonNullable<Awaited<ReturnType<typeof playerControllerPrevious>>>;

export type PlayerControllerPreviousMutationError = unknown;

/**
 * @summary 이전 곡
 */
export const usePlayerControllerPrevious = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playerControllerPrevious>>,
      TError,
      { roomId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof playerControllerPrevious>>, TError, { roomId: string }, TContext> => {
  const mutationOptions = getPlayerControllerPreviousMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 투표 스킵
 */
export const getPlayerControllerVoteSkipUrl = (roomId: string) => {
  return `/api/player/${roomId}/vote-skip`;
};

export const playerControllerVoteSkip = async (roomId: string, options?: RequestInit): Promise<VoteSkipResponse> => {
  return customFetch<VoteSkipResponse>(getPlayerControllerVoteSkipUrl(roomId), {
    ...options,
    method: 'POST',
  });
};

export const getPlayerControllerVoteSkipMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof playerControllerVoteSkip>>,
    TError,
    { roomId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof playerControllerVoteSkip>>, TError, { roomId: string }, TContext> => {
  const mutationKey = ['playerControllerVoteSkip'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof playerControllerVoteSkip>>, { roomId: string }> = (
    props,
  ) => {
    const { roomId } = props ?? {};

    return playerControllerVoteSkip(roomId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlayerControllerVoteSkipMutationResult = NonNullable<Awaited<ReturnType<typeof playerControllerVoteSkip>>>;

export type PlayerControllerVoteSkipMutationError = unknown;

/**
 * @summary 투표 스킵
 */
export const usePlayerControllerVoteSkip = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof playerControllerVoteSkip>>,
      TError,
      { roomId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof playerControllerVoteSkip>>, TError, { roomId: string }, TContext> => {
  const mutationOptions = getPlayerControllerVoteSkipMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 가사 조회
 */
export const getPlayerControllerLyricsUrl = (roomId: string) => {
  return `/api/player/${roomId}/lyrics`;
};

export const playerControllerLyrics = async (roomId: string, options?: RequestInit): Promise<LyricsResponse> => {
  return customFetch<LyricsResponse>(getPlayerControllerLyricsUrl(roomId), {
    ...options,
    method: 'GET',
  });
};

export const getPlayerControllerLyricsQueryKey = (roomId?: string) => {
  return [`/api/player/${roomId}/lyrics`] as const;
};

export const getPlayerControllerLyricsQueryOptions = <
  TData = Awaited<ReturnType<typeof playerControllerLyrics>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerLyrics>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPlayerControllerLyricsQueryKey(roomId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof playerControllerLyrics>>> = ({ signal }) =>
    playerControllerLyrics(roomId, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!roomId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof playerControllerLyrics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PlayerControllerLyricsQueryResult = NonNullable<Awaited<ReturnType<typeof playerControllerLyrics>>>;
export type PlayerControllerLyricsQueryError = unknown;

export function usePlayerControllerLyrics<TData = Awaited<ReturnType<typeof playerControllerLyrics>>, TError = unknown>(
  roomId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerLyrics>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof playerControllerLyrics>>,
          TError,
          Awaited<ReturnType<typeof playerControllerLyrics>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePlayerControllerLyrics<TData = Awaited<ReturnType<typeof playerControllerLyrics>>, TError = unknown>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerLyrics>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof playerControllerLyrics>>,
          TError,
          Awaited<ReturnType<typeof playerControllerLyrics>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePlayerControllerLyrics<TData = Awaited<ReturnType<typeof playerControllerLyrics>>, TError = unknown>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerLyrics>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 가사 조회
 */

export function usePlayerControllerLyrics<TData = Awaited<ReturnType<typeof playerControllerLyrics>>, TError = unknown>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerLyrics>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPlayerControllerLyricsQueryOptions(roomId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 재생 상태 조회
 */
export const getPlayerControllerGetStatusUrl = (roomId: string) => {
  return `/api/player/${roomId}`;
};

export const playerControllerGetStatus = async (roomId: string, options?: RequestInit): Promise<PlaybackStatus> => {
  return customFetch<PlaybackStatus>(getPlayerControllerGetStatusUrl(roomId), {
    ...options,
    method: 'GET',
  });
};

export const getPlayerControllerGetStatusQueryKey = (roomId?: string) => {
  return [`/api/player/${roomId}`] as const;
};

export const getPlayerControllerGetStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof playerControllerGetStatus>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerGetStatus>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPlayerControllerGetStatusQueryKey(roomId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof playerControllerGetStatus>>> = ({ signal }) =>
    playerControllerGetStatus(roomId, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!roomId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof playerControllerGetStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PlayerControllerGetStatusQueryResult = NonNullable<Awaited<ReturnType<typeof playerControllerGetStatus>>>;
export type PlayerControllerGetStatusQueryError = unknown;

export function usePlayerControllerGetStatus<
  TData = Awaited<ReturnType<typeof playerControllerGetStatus>>,
  TError = unknown,
>(
  roomId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerGetStatus>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof playerControllerGetStatus>>,
          TError,
          Awaited<ReturnType<typeof playerControllerGetStatus>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePlayerControllerGetStatus<
  TData = Awaited<ReturnType<typeof playerControllerGetStatus>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerGetStatus>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof playerControllerGetStatus>>,
          TError,
          Awaited<ReturnType<typeof playerControllerGetStatus>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePlayerControllerGetStatus<
  TData = Awaited<ReturnType<typeof playerControllerGetStatus>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerGetStatus>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 재생 상태 조회
 */

export function usePlayerControllerGetStatus<
  TData = Awaited<ReturnType<typeof playerControllerGetStatus>>,
  TError = unknown,
>(
  roomId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerGetStatus>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPlayerControllerGetStatusQueryOptions(roomId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
